from dataclasses import dataclass
from typing import Optional, Dict

from BaseClasses import Item, ItemClassification
from .Names import ItemName

base_item_id: int = 400000


class LB1Item(Item):
    game: str = "Lego Batman: The Video Game"


@dataclass
class LB1ItemData:
    code: Optional[int] = None
    classification: ItemClassification = ItemClassification.filler
    type: str = "Minikit"


character_item_table: Dict[str, LB1ItemData] = {
    # ItemName.batman_unlocked: LB1ItemData(base_item_id + 0, ItemClassification.progression, "Character"),
    # ItemName.robin_unlocked: LB1ItemData(base_item_id + 1, ItemClassification.progression, "Character"),
    ItemName.brucewayne_unlocked: LB1ItemData(base_item_id + 2, ItemClassification.filler, "Character"),
    ItemName.alfred_unlocked: LB1ItemData(base_item_id + 3, ItemClassification.filler, "Character"),
    ItemName.batgirl_unlocked: LB1ItemData(base_item_id + 4, ItemClassification.progression_deprioritized, "Character"),
    ItemName.nightwing_unlocked: LB1ItemData(base_item_id + 5,
                                             ItemClassification.progression_deprioritized, "Character"),
    ItemName.commissionergordon_unlocked: LB1ItemData(base_item_id + 6, ItemClassification.filler, "Character"),
    ItemName.policeofficer_unlocked: LB1ItemData(base_item_id + 7, ItemClassification.filler, "Character"),
    ItemName.fishmonger_unlocked: LB1ItemData(base_item_id + 8, ItemClassification.filler, "Character"),
    ItemName.militarypoliceman_unlocked: LB1ItemData(base_item_id + 9, ItemClassification.filler, "Character"),
    ItemName.securityguard_unlocked: LB1ItemData(base_item_id + 10, ItemClassification.filler, "Character"),
    ItemName.swat_unlocked: LB1ItemData(base_item_id + 11, ItemClassification.filler, "Character"),
    ItemName.scientist_unlocked: LB1ItemData(base_item_id + 12,
                                             ItemClassification.progression_deprioritized, "Character"),
    ItemName.sailor_unlocked: LB1ItemData(base_item_id + 13, ItemClassification.filler, "Character"),
    ItemName.policemarksman_unlocked: LB1ItemData(base_item_id + 14, ItemClassification.filler, "Character"),
    ItemName.clayface_unlocked: LB1ItemData(base_item_id + 15, ItemClassification.progression, "Character"),
    ItemName.mrfreeze_unlocked: LB1ItemData(base_item_id + 16, ItemClassification.progression, "Character"),
    ItemName.poisonivy_unlocked: LB1ItemData(base_item_id + 17, ItemClassification.progression, "Character"),
    ItemName.twoface_unlocked: LB1ItemData(base_item_id + 18, ItemClassification.progression, "Character"),
    ItemName.riddler_unlocked: LB1ItemData(base_item_id + 19, ItemClassification.progression, "Character"),
    ItemName.bane_unlocked: LB1ItemData(base_item_id + 20, ItemClassification.progression, "Character"),
    ItemName.catwoman_unlocked: LB1ItemData(base_item_id + 21, ItemClassification.progression, "Character"),
    ItemName.catwomanclassic_unlocked: LB1ItemData(base_item_id + 22, ItemClassification.progression, "Character"),
    ItemName.killercroc_unlocked: LB1ItemData(base_item_id + 23, ItemClassification.progression, "Character"),
    ItemName.manbat_unlocked: LB1ItemData(base_item_id + 24, ItemClassification.progression, "Character"),
    ItemName.penguin_unlocked: LB1ItemData(base_item_id + 25, ItemClassification.progression, "Character"),
    ItemName.harleyquinn_unlocked: LB1ItemData(base_item_id + 26, ItemClassification.progression, "Character"),
    ItemName.scarecrow_unlocked: LB1ItemData(base_item_id + 27, ItemClassification.progression, "Character"),
    ItemName.killermoth_unlocked: LB1ItemData(base_item_id + 28, ItemClassification.progression, "Character"),
    ItemName.madhatter_unlocked: LB1ItemData(base_item_id + 29, ItemClassification.progression, "Character"),
    ItemName.joker_unlocked: LB1ItemData(base_item_id + 30, ItemClassification.progression, "Character"),
    ItemName.jokertropical_unlocked: LB1ItemData(base_item_id + 31, ItemClassification.progression, "Character"),
    ItemName.poisonivygoon_unlocked: LB1ItemData(base_item_id + 32, ItemClassification.filler, "Character"),
    ItemName.zoosweeper_unlocked: LB1ItemData(base_item_id + 33, ItemClassification.filler, "Character"),
    ItemName.freezegirl_unlocked: LB1ItemData(base_item_id + 34, ItemClassification.filler, "Character"),
    ItemName.yeti_unlocked: LB1ItemData(base_item_id + 35, ItemClassification.filler, "Character"),
    ItemName.riddlergoon_unlocked: LB1ItemData(base_item_id + 36, ItemClassification.filler, "Character"),
    ItemName.riddlerhenchman_unlocked: LB1ItemData(base_item_id + 37, ItemClassification.filler, "Character"),
    ItemName.penguingoon_unlocked: LB1ItemData(base_item_id + 38, ItemClassification.filler, "Character"),
    ItemName.penguinhenchman_unlocked: LB1ItemData(base_item_id + 39, ItemClassification.filler, "Character"),
    ItemName.penguinminion_unlocked: LB1ItemData(base_item_id + 40, ItemClassification.useful, "Character"),
    ItemName.jokergoon_unlocked: LB1ItemData(base_item_id + 41, ItemClassification.progression, "Character"),
    ItemName.jokerhenchman_unlocked: LB1ItemData(base_item_id + 42, ItemClassification.filler, "Character"),
    ItemName.clowngoon_unlocked: LB1ItemData(base_item_id + 43, ItemClassification.filler, "Character"),
    ItemName.hush_unlocked: LB1ItemData(base_item_id + 44, ItemClassification.useful, "Hard Character"),
    ItemName.rasalghul_unlocked: LB1ItemData(base_item_id + 45, ItemClassification.useful, "Hard Character"),
    # ItemName.hero1_unlocked: LB1ItemData(base_item_id + 46, ItemClassification.progression, "Character"),
    # ItemName.hero2_unlocked: LB1ItemData(base_item_id + 47, ItemClassification.progression, "Character"),
    ItemName.batmobile_unlocked: LB1ItemData(base_item_id + 48, ItemClassification.progression, "Character"),
    ItemName.batcycle_unlocked: LB1ItemData(base_item_id + 49, ItemClassification.progression, "Character"),
    ItemName.policecar_unlocked: LB1ItemData(base_item_id + 50,
                                             ItemClassification.progression_deprioritized, "Character"),
    ItemName.policebike_unlocked: LB1ItemData(base_item_id + 51, ItemClassification.filler, "Character"),
    ItemName.policevan_unlocked: LB1ItemData(base_item_id + 52,
                                             ItemClassification.progression_deprioritized, "Character"),
    ItemName.battank_unlocked: LB1ItemData(base_item_id + 53,
                                           ItemClassification.progression_deprioritized, "Character"),
    ItemName.catmotorcycle_unlocked: LB1ItemData(base_item_id + 54,
                                                 ItemClassification.progression_deprioritized, "Character"),
    ItemName.armouredtruck_unlocked: LB1ItemData(base_item_id + 55, ItemClassification.filler, "Character"),
    ItemName.freezekart_unlocked: LB1ItemData(base_item_id + 56,
                                              ItemClassification.progression_deprioritized, "Character"),
    ItemName.hammertruck_unlocked: LB1ItemData(base_item_id + 57,
                                               ItemClassification.progression_deprioritized, "Character"),
    ItemName.jokervan_unlocked: LB1ItemData(base_item_id + 58,
                                            ItemClassification.progression_deprioritized, "Character"),
    ItemName.garbagetruck_unlocked: LB1ItemData(base_item_id + 59,
                                                ItemClassification.progression_deprioritized, "Character"),
    ItemName.batboat_unlocked: LB1ItemData(base_item_id + 60, ItemClassification.progression, "Character"),
    ItemName.robinswatercraft_unlocked: LB1ItemData(base_item_id + 61, ItemClassification.progression, "Character"),
    ItemName.robinssubmarine_unlocked: LB1ItemData(base_item_id + 62,
                                                   ItemClassification.progression_deprioritized, "Character"),
    ItemName.policewatercraft_unlocked: LB1ItemData(base_item_id + 63,
                                                    ItemClassification.progression_deprioritized, "Character"),
    ItemName.policeboat_unlocked: LB1ItemData(base_item_id + 64, ItemClassification.filler, "Character"),
    ItemName.penguinsubmarine_unlocked: LB1ItemData(base_item_id + 65, ItemClassification.progression, "Character"),
    ItemName.swamprider_unlocked: LB1ItemData(base_item_id + 66, ItemClassification.progression, "Character"),
    ItemName.penguingoonsub_unlocked: LB1ItemData(base_item_id + 67,
                                                  ItemClassification.progression_deprioritized, "Character"),
    ItemName.iceberg_unlocked: LB1ItemData(base_item_id + 68,
                                           ItemClassification.progression_deprioritized, "Character"),
    ItemName.steamboat_unlocked: LB1ItemData(base_item_id + 69, ItemClassification.filler, "Character"),
    ItemName.batwing_unlocked: LB1ItemData(base_item_id + 70, ItemClassification.progression, "Character"),
    ItemName.batcopter_unlocked: LB1ItemData(base_item_id + 71, ItemClassification.progression, "Character"),
    ItemName.harbourhelicopter_unlocked: LB1ItemData(base_item_id + 72,
                                                     ItemClassification.progression_deprioritized, "Character"),
    ItemName.policehelicopter_unlocked: LB1ItemData(base_item_id + 73,
                                                    ItemClassification.progression_deprioritized, "Character"),
    ItemName.privatejet_unlocked: LB1ItemData(base_item_id + 74, ItemClassification.filler, "Character"),
    ItemName.jokerhelicopter_unlocked: LB1ItemData(base_item_id + 75, ItemClassification.progression, "Character"),
    ItemName.scarecrowbiplane_unlocked: LB1ItemData(base_item_id + 76, ItemClassification.progression, "Character"),
    ItemName.goonhelicopter_unlocked: LB1ItemData(base_item_id + 77,
                                                  ItemClassification.progression_deprioritized, "Character"),
    ItemName.riddlerjet_unlocked: LB1ItemData(base_item_id + 78,
                                              ItemClassification.progression_deprioritized, "Character"),
    ItemName.glider_unlocked: LB1ItemData(base_item_id + 79, ItemClassification.filler, "Character"),
}

# Currently stored in Batcave because it is sounding like they can be unlocked in multiple levels
# suit_item_table: Dict[str, LB1ItemData] = {
#     # "Batsuit": LB1ItemData(base_item_id + 80, ItemClassification.progression),
#     ItemName.heatprotectsuit: LB1ItemData(base_item_id + 81, ItemClassification.progression, "Suit"),
#     ItemName.glidesuit: LB1ItemData(base_item_id + 82, ItemClassification.progression, "Suit"),
#     ItemName.demolitionsuit: LB1ItemData(base_item_id + 83, ItemClassification.progression, "Suit"),
#     ItemName.sonicsuit: LB1ItemData(base_item_id + 84, ItemClassification.progression, "Suit"),
#     # "Robinsuit": LB1ItemData(base_item_id + 85, ItemClassification.progression),
#     ItemName.watersuit: LB1ItemData(base_item_id + 86, ItemClassification.progression, "Suit"),
#     ItemName.techsuit: LB1ItemData(base_item_id + 87, ItemClassification.progression, "Suit"),
#     ItemName.magsuit: LB1ItemData(base_item_id + 88, ItemClassification.progression, "Suit"),
#     ItemName.attractsuit: LB1ItemData(base_item_id + 89, ItemClassification.progression, "Suit"),
# }

filler_item_table: Dict[str, LB1ItemData] = {
    "Nothing": LB1ItemData(base_item_id + 90, ItemClassification.filler, "Nothing"),
}

minikit_item_table: Dict[str, LB1ItemData] = {
    ItemName.ycbob_min1: LB1ItemData(base_item_id + 100),
    ItemName.ycbob_min2: LB1ItemData(base_item_id + 101),
    ItemName.ycbob_min3: LB1ItemData(base_item_id + 102),
    ItemName.ycbob_min4: LB1ItemData(base_item_id + 103),
    ItemName.ycbob_min5: LB1ItemData(base_item_id + 104),
    ItemName.ycbob_min6: LB1ItemData(base_item_id + 105),
    ItemName.ycbob_min7: LB1ItemData(base_item_id + 106),
    ItemName.ycbob_min8: LB1ItemData(base_item_id + 107),
    ItemName.ycbob_min9: LB1ItemData(base_item_id + 108),
    ItemName.ycbob_min10: LB1ItemData(base_item_id + 109),

    ItemName.air_min1: LB1ItemData(base_item_id + 110),
    ItemName.air_min2: LB1ItemData(base_item_id + 111),
    ItemName.air_min3: LB1ItemData(base_item_id + 112),
    ItemName.air_min4: LB1ItemData(base_item_id + 113),
    ItemName.air_min5: LB1ItemData(base_item_id + 114),
    ItemName.air_min6: LB1ItemData(base_item_id + 115),
    ItemName.air_min7: LB1ItemData(base_item_id + 116),
    ItemName.air_min8: LB1ItemData(base_item_id + 117),
    ItemName.air_min9: LB1ItemData(base_item_id + 118),
    ItemName.air_min10: LB1ItemData(base_item_id + 119),

    ItemName.tfc_min1: LB1ItemData(base_item_id + 120),
    ItemName.tfc_min2: LB1ItemData(base_item_id + 121),
    ItemName.tfc_min3: LB1ItemData(base_item_id + 122),
    ItemName.tfc_min4: LB1ItemData(base_item_id + 123),
    ItemName.tfc_min5: LB1ItemData(base_item_id + 124),
    ItemName.tfc_min6: LB1ItemData(base_item_id + 125),
    ItemName.tfc_min7: LB1ItemData(base_item_id + 126),
    ItemName.tfc_min8: LB1ItemData(base_item_id + 127),
    ItemName.tfc_min9: LB1ItemData(base_item_id + 128),
    ItemName.tfc_min10: LB1ItemData(base_item_id + 129),

    ItemName.apa_min1: LB1ItemData(base_item_id + 130),
    ItemName.apa_min2: LB1ItemData(base_item_id + 131),
    ItemName.apa_min3: LB1ItemData(base_item_id + 132),
    ItemName.apa_min4: LB1ItemData(base_item_id + 133),
    ItemName.apa_min5: LB1ItemData(base_item_id + 134),
    ItemName.apa_min6: LB1ItemData(base_item_id + 135),
    ItemName.apa_min7: LB1ItemData(base_item_id + 136),
    ItemName.apa_min8: LB1ItemData(base_item_id + 137),
    ItemName.apa_min9: LB1ItemData(base_item_id + 138),
    ItemName.apa_min10: LB1ItemData(base_item_id + 139),

    ItemName.tfo_min1: LB1ItemData(base_item_id + 140),
    ItemName.tfo_min2: LB1ItemData(base_item_id + 141),
    ItemName.tfo_min3: LB1ItemData(base_item_id + 142),
    ItemName.tfo_min4: LB1ItemData(base_item_id + 143),
    ItemName.tfo_min5: LB1ItemData(base_item_id + 144),
    ItemName.tfo_min6: LB1ItemData(base_item_id + 145),
    ItemName.tfo_min7: LB1ItemData(base_item_id + 146),
    ItemName.tfo_min8: LB1ItemData(base_item_id + 147),
    ItemName.tfo_min9: LB1ItemData(base_item_id + 148),
    ItemName.tfo_min10: LB1ItemData(base_item_id + 149),

    ItemName.tsga_min1: LB1ItemData(base_item_id + 150),
    ItemName.tsga_min2: LB1ItemData(base_item_id + 151),
    ItemName.tsga_min3: LB1ItemData(base_item_id + 152),
    ItemName.tsga_min4: LB1ItemData(base_item_id + 153),
    ItemName.tsga_min5: LB1ItemData(base_item_id + 154),
    ItemName.tsga_min6: LB1ItemData(base_item_id + 155),
    ItemName.tsga_min7: LB1ItemData(base_item_id + 156),
    ItemName.tsga_min8: LB1ItemData(base_item_id + 157),
    ItemName.tsga_min9: LB1ItemData(base_item_id + 158),
    ItemName.tsga_min10: LB1ItemData(base_item_id + 159),

    ItemName.bbb_min1: LB1ItemData(base_item_id + 160),
    ItemName.bbb_min2: LB1ItemData(base_item_id + 161),
    ItemName.bbb_min3: LB1ItemData(base_item_id + 162),
    ItemName.bbb_min4: LB1ItemData(base_item_id + 163),
    ItemName.bbb_min5: LB1ItemData(base_item_id + 164),
    ItemName.bbb_min6: LB1ItemData(base_item_id + 165),
    ItemName.bbb_min7: LB1ItemData(base_item_id + 166),
    ItemName.bbb_min8: LB1ItemData(base_item_id + 167),
    ItemName.bbb_min9: LB1ItemData(base_item_id + 168),
    ItemName.bbb_min10: LB1ItemData(base_item_id + 169),

    ItemName.utc_min1: LB1ItemData(base_item_id + 170),
    ItemName.utc_min2: LB1ItemData(base_item_id + 171),
    ItemName.utc_min3: LB1ItemData(base_item_id + 172),
    ItemName.utc_min4: LB1ItemData(base_item_id + 173),
    ItemName.utc_min5: LB1ItemData(base_item_id + 174),
    ItemName.utc_min6: LB1ItemData(base_item_id + 175),
    ItemName.utc_min7: LB1ItemData(base_item_id + 176),
    ItemName.utc_min8: LB1ItemData(base_item_id + 177),
    ItemName.utc_min9: LB1ItemData(base_item_id + 178),
    ItemName.utc_min10: LB1ItemData(base_item_id + 179),

    ItemName.zc_min1: LB1ItemData(base_item_id + 180),
    ItemName.zc_min2: LB1ItemData(base_item_id + 181),
    ItemName.zc_min3: LB1ItemData(base_item_id + 182),
    ItemName.zc_min4: LB1ItemData(base_item_id + 183),
    ItemName.zc_min5: LB1ItemData(base_item_id + 184),
    ItemName.zc_min6: LB1ItemData(base_item_id + 185),
    ItemName.zc_min7: LB1ItemData(base_item_id + 186),
    ItemName.zc_min8: LB1ItemData(base_item_id + 187),
    ItemName.zc_min9: LB1ItemData(base_item_id + 188),
    ItemName.zc_min10: LB1ItemData(base_item_id + 189),

    ItemName.pl_min1: LB1ItemData(base_item_id + 190),
    ItemName.pl_min2: LB1ItemData(base_item_id + 191),
    ItemName.pl_min3: LB1ItemData(base_item_id + 192),
    ItemName.pl_min4: LB1ItemData(base_item_id + 193),
    ItemName.pl_min5: LB1ItemData(base_item_id + 194),
    ItemName.pl_min6: LB1ItemData(base_item_id + 195),
    ItemName.pl_min7: LB1ItemData(base_item_id + 196),
    ItemName.pl_min8: LB1ItemData(base_item_id + 197),
    ItemName.pl_min9: LB1ItemData(base_item_id + 198),
    ItemName.pl_min10: LB1ItemData(base_item_id + 199),

    ItemName.jht_min1: LB1ItemData(base_item_id + 200),
    ItemName.jht_min2: LB1ItemData(base_item_id + 201),
    ItemName.jht_min3: LB1ItemData(base_item_id + 202),
    ItemName.jht_min4: LB1ItemData(base_item_id + 203),
    ItemName.jht_min5: LB1ItemData(base_item_id + 204),
    ItemName.jht_min6: LB1ItemData(base_item_id + 205),
    ItemName.jht_min7: LB1ItemData(base_item_id + 206),
    ItemName.jht_min8: LB1ItemData(base_item_id + 207),
    ItemName.jht_min9: LB1ItemData(base_item_id + 208),
    ItemName.jht_min10: LB1ItemData(base_item_id + 209),

    ItemName.lfabt_min1: LB1ItemData(base_item_id + 210),
    ItemName.lfabt_min2: LB1ItemData(base_item_id + 211),
    ItemName.lfabt_min3: LB1ItemData(base_item_id + 212),
    ItemName.lfabt_min4: LB1ItemData(base_item_id + 213),
    ItemName.lfabt_min5: LB1ItemData(base_item_id + 214),
    ItemName.lfabt_min6: LB1ItemData(base_item_id + 215),
    ItemName.lfabt_min7: LB1ItemData(base_item_id + 216),
    ItemName.lfabt_min8: LB1ItemData(base_item_id + 217),
    ItemName.lfabt_min9: LB1ItemData(base_item_id + 218),
    ItemName.lfabt_min10: LB1ItemData(base_item_id + 219),

    ItemName.fotb_min1: LB1ItemData(base_item_id + 220),
    ItemName.fotb_min2: LB1ItemData(base_item_id + 221),
    ItemName.fotb_min3: LB1ItemData(base_item_id + 222),
    ItemName.fotb_min4: LB1ItemData(base_item_id + 223),
    ItemName.fotb_min5: LB1ItemData(base_item_id + 224),
    ItemName.fotb_min6: LB1ItemData(base_item_id + 225),
    ItemName.fotb_min7: LB1ItemData(base_item_id + 226),
    ItemName.fotb_min8: LB1ItemData(base_item_id + 227),
    ItemName.fotb_min9: LB1ItemData(base_item_id + 228),
    ItemName.fotb_min10: LB1ItemData(base_item_id + 229),

    ItemName.itdn_min1: LB1ItemData(base_item_id + 230),
    ItemName.itdn_min2: LB1ItemData(base_item_id + 231),
    ItemName.itdn_min3: LB1ItemData(base_item_id + 232),
    ItemName.itdn_min4: LB1ItemData(base_item_id + 233),
    ItemName.itdn_min5: LB1ItemData(base_item_id + 234),
    ItemName.itdn_min6: LB1ItemData(base_item_id + 235),
    ItemName.itdn_min7: LB1ItemData(base_item_id + 236),
    ItemName.itdn_min8: LB1ItemData(base_item_id + 237),
    ItemName.itdn_min9: LB1ItemData(base_item_id + 238),
    ItemName.itdn_min10: LB1ItemData(base_item_id + 239),

    ItemName.tttot_min1: LB1ItemData(base_item_id + 240),
    ItemName.tttot_min2: LB1ItemData(base_item_id + 241),
    ItemName.tttot_min3: LB1ItemData(base_item_id + 242),
    ItemName.tttot_min4: LB1ItemData(base_item_id + 243),
    ItemName.tttot_min5: LB1ItemData(base_item_id + 244),
    ItemName.tttot_min6: LB1ItemData(base_item_id + 245),
    ItemName.tttot_min7: LB1ItemData(base_item_id + 246),
    ItemName.tttot_min8: LB1ItemData(base_item_id + 247),
    ItemName.tttot_min9: LB1ItemData(base_item_id + 248),
    ItemName.tttot_min10: LB1ItemData(base_item_id + 249),

    ItemName.trmaw_min1: LB1ItemData(base_item_id + 250),
    ItemName.trmaw_min2: LB1ItemData(base_item_id + 251),
    ItemName.trmaw_min3: LB1ItemData(base_item_id + 252),
    ItemName.trmaw_min4: LB1ItemData(base_item_id + 253),
    ItemName.trmaw_min5: LB1ItemData(base_item_id + 254),
    ItemName.trmaw_min6: LB1ItemData(base_item_id + 255),
    ItemName.trmaw_min7: LB1ItemData(base_item_id + 256),
    ItemName.trmaw_min8: LB1ItemData(base_item_id + 257),
    ItemName.trmaw_min9: LB1ItemData(base_item_id + 258),
    ItemName.trmaw_min10: LB1ItemData(base_item_id + 259),

    ItemName.otr_min1: LB1ItemData(base_item_id + 260),
    ItemName.otr_min2: LB1ItemData(base_item_id + 261),
    ItemName.otr_min3: LB1ItemData(base_item_id + 262),
    ItemName.otr_min4: LB1ItemData(base_item_id + 263),
    ItemName.otr_min5: LB1ItemData(base_item_id + 264),
    ItemName.otr_min6: LB1ItemData(base_item_id + 265),
    ItemName.otr_min7: LB1ItemData(base_item_id + 266),
    ItemName.otr_min8: LB1ItemData(base_item_id + 267),
    ItemName.otr_min9: LB1ItemData(base_item_id + 268),
    ItemName.otr_min10: LB1ItemData(base_item_id + 269),

    ItemName.gf_min1: LB1ItemData(base_item_id + 270),
    ItemName.gf_min2: LB1ItemData(base_item_id + 271),
    ItemName.gf_min3: LB1ItemData(base_item_id + 272),
    ItemName.gf_min4: LB1ItemData(base_item_id + 273),
    ItemName.gf_min5: LB1ItemData(base_item_id + 274),
    ItemName.gf_min6: LB1ItemData(base_item_id + 275),
    ItemName.gf_min7: LB1ItemData(base_item_id + 276),
    ItemName.gf_min8: LB1ItemData(base_item_id + 277),
    ItemName.gf_min9: LB1ItemData(base_item_id + 278),
    ItemName.gf_min10: LB1ItemData(base_item_id + 279),

    ItemName.aet_min1: LB1ItemData(base_item_id + 280),
    ItemName.aet_min2: LB1ItemData(base_item_id + 281),
    ItemName.aet_min3: LB1ItemData(base_item_id + 282),
    ItemName.aet_min4: LB1ItemData(base_item_id + 283),
    ItemName.aet_min5: LB1ItemData(base_item_id + 284),
    ItemName.aet_min6: LB1ItemData(base_item_id + 285),
    ItemName.aet_min7: LB1ItemData(base_item_id + 286),
    ItemName.aet_min8: LB1ItemData(base_item_id + 287),
    ItemName.aet_min9: LB1ItemData(base_item_id + 288),
    ItemName.aet_min10: LB1ItemData(base_item_id + 289),

    ItemName.bb_min1: LB1ItemData(base_item_id + 290),
    ItemName.bb_min2: LB1ItemData(base_item_id + 291),
    ItemName.bb_min3: LB1ItemData(base_item_id + 292),
    ItemName.bb_min4: LB1ItemData(base_item_id + 293),
    ItemName.bb_min5: LB1ItemData(base_item_id + 294),
    ItemName.bb_min6: LB1ItemData(base_item_id + 295),
    ItemName.bb_min7: LB1ItemData(base_item_id + 296),
    ItemName.bb_min8: LB1ItemData(base_item_id + 297),
    ItemName.bb_min9: LB1ItemData(base_item_id + 298),
    ItemName.bb_min10: LB1ItemData(base_item_id + 299),

    ItemName.rtd_min1: LB1ItemData(base_item_id + 300),
    ItemName.rtd_min2: LB1ItemData(base_item_id + 301),
    ItemName.rtd_min3: LB1ItemData(base_item_id + 302),
    ItemName.rtd_min4: LB1ItemData(base_item_id + 303),
    ItemName.rtd_min5: LB1ItemData(base_item_id + 304),
    ItemName.rtd_min6: LB1ItemData(base_item_id + 305),
    ItemName.rtd_min7: LB1ItemData(base_item_id + 306),
    ItemName.rtd_min8: LB1ItemData(base_item_id + 307),
    ItemName.rtd_min9: LB1ItemData(base_item_id + 308),
    ItemName.rtd_min10: LB1ItemData(base_item_id + 309),

    ItemName.sts_min1: LB1ItemData(base_item_id + 310),
    ItemName.sts_min2: LB1ItemData(base_item_id + 311),
    ItemName.sts_min3: LB1ItemData(base_item_id + 312),
    ItemName.sts_min4: LB1ItemData(base_item_id + 313),
    ItemName.sts_min5: LB1ItemData(base_item_id + 314),
    ItemName.sts_min6: LB1ItemData(base_item_id + 315),
    ItemName.sts_min7: LB1ItemData(base_item_id + 316),
    ItemName.sts_min8: LB1ItemData(base_item_id + 317),
    ItemName.sts_min9: LB1ItemData(base_item_id + 318),
    ItemName.sts_min10: LB1ItemData(base_item_id + 319),

    ItemName.hag_min1: LB1ItemData(base_item_id + 320),
    ItemName.hag_min2: LB1ItemData(base_item_id + 321),
    ItemName.hag_min3: LB1ItemData(base_item_id + 322),
    ItemName.hag_min4: LB1ItemData(base_item_id + 323),
    ItemName.hag_min5: LB1ItemData(base_item_id + 324),
    ItemName.hag_min6: LB1ItemData(base_item_id + 325),
    ItemName.hag_min7: LB1ItemData(base_item_id + 326),
    ItemName.hag_min8: LB1ItemData(base_item_id + 327),
    ItemName.hag_min9: LB1ItemData(base_item_id + 328),
    ItemName.hag_min10: LB1ItemData(base_item_id + 329),

    ItemName.adr_min1: LB1ItemData(base_item_id + 330),
    ItemName.adr_min2: LB1ItemData(base_item_id + 331),
    ItemName.adr_min3: LB1ItemData(base_item_id + 332),
    ItemName.adr_min4: LB1ItemData(base_item_id + 333),
    ItemName.adr_min5: LB1ItemData(base_item_id + 334),
    ItemName.adr_min6: LB1ItemData(base_item_id + 335),
    ItemName.adr_min7: LB1ItemData(base_item_id + 336),
    ItemName.adr_min8: LB1ItemData(base_item_id + 337),
    ItemName.adr_min9: LB1ItemData(base_item_id + 338),
    ItemName.adr_min10: LB1ItemData(base_item_id + 339),

    ItemName.aw_min1: LB1ItemData(base_item_id + 340),
    ItemName.aw_min2: LB1ItemData(base_item_id + 341),
    ItemName.aw_min3: LB1ItemData(base_item_id + 342),
    ItemName.aw_min4: LB1ItemData(base_item_id + 343),
    ItemName.aw_min5: LB1ItemData(base_item_id + 344),
    ItemName.aw_min6: LB1ItemData(base_item_id + 345),
    ItemName.aw_min7: LB1ItemData(base_item_id + 346),
    ItemName.aw_min8: LB1ItemData(base_item_id + 347),
    ItemName.aw_min9: LB1ItemData(base_item_id + 348),
    ItemName.aw_min10: LB1ItemData(base_item_id + 349),

    ItemName.asftc_min1: LB1ItemData(base_item_id + 350),
    ItemName.asftc_min2: LB1ItemData(base_item_id + 351),
    ItemName.asftc_min3: LB1ItemData(base_item_id + 352),
    ItemName.asftc_min4: LB1ItemData(base_item_id + 353),
    ItemName.asftc_min5: LB1ItemData(base_item_id + 354),
    ItemName.asftc_min6: LB1ItemData(base_item_id + 355),
    ItemName.asftc_min7: LB1ItemData(base_item_id + 356),
    ItemName.asftc_min8: LB1ItemData(base_item_id + 357),
    ItemName.asftc_min9: LB1ItemData(base_item_id + 358),
    ItemName.asftc_min10: LB1ItemData(base_item_id + 359),

    ItemName.bbpl_min1: LB1ItemData(base_item_id + 360),
    ItemName.bbpl_min2: LB1ItemData(base_item_id + 361),
    ItemName.bbpl_min3: LB1ItemData(base_item_id + 362),
    ItemName.bbpl_min4: LB1ItemData(base_item_id + 363),
    ItemName.bbpl_min5: LB1ItemData(base_item_id + 364),
    ItemName.bbpl_min6: LB1ItemData(base_item_id + 365),
    ItemName.bbpl_min7: LB1ItemData(base_item_id + 366),
    ItemName.bbpl_min8: LB1ItemData(base_item_id + 367),
    ItemName.bbpl_min9: LB1ItemData(base_item_id + 368),
    ItemName.bbpl_min10: LB1ItemData(base_item_id + 369),

    ItemName.tjm_min1: LB1ItemData(base_item_id + 370),
    ItemName.tjm_min2: LB1ItemData(base_item_id + 371),
    ItemName.tjm_min3: LB1ItemData(base_item_id + 372),
    ItemName.tjm_min4: LB1ItemData(base_item_id + 373),
    ItemName.tjm_min5: LB1ItemData(base_item_id + 374),
    ItemName.tjm_min6: LB1ItemData(base_item_id + 375),
    ItemName.tjm_min7: LB1ItemData(base_item_id + 376),
    ItemName.tjm_min8: LB1ItemData(base_item_id + 377),
    ItemName.tjm_min9: LB1ItemData(base_item_id + 378),
    ItemName.tjm_min10: LB1ItemData(base_item_id + 379),

    ItemName.tlotn_min1: LB1ItemData(base_item_id + 380),
    ItemName.tlotn_min2: LB1ItemData(base_item_id + 381),
    ItemName.tlotn_min3: LB1ItemData(base_item_id + 382),
    ItemName.tlotn_min4: LB1ItemData(base_item_id + 383),
    ItemName.tlotn_min5: LB1ItemData(base_item_id + 384),
    ItemName.tlotn_min6: LB1ItemData(base_item_id + 385),
    ItemName.tlotn_min7: LB1ItemData(base_item_id + 386),
    ItemName.tlotn_min8: LB1ItemData(base_item_id + 387),
    ItemName.tlotn_min9: LB1ItemData(base_item_id + 388),
    ItemName.tlotn_min10: LB1ItemData(base_item_id + 389),

    ItemName.dol_min1: LB1ItemData(base_item_id + 390),
    ItemName.dol_min2: LB1ItemData(base_item_id + 391),
    ItemName.dol_min3: LB1ItemData(base_item_id + 392),
    ItemName.dol_min4: LB1ItemData(base_item_id + 393),
    ItemName.dol_min5: LB1ItemData(base_item_id + 394),
    ItemName.dol_min6: LB1ItemData(base_item_id + 395),
    ItemName.dol_min7: LB1ItemData(base_item_id + 396),
    ItemName.dol_min8: LB1ItemData(base_item_id + 397),
    ItemName.dol_min9: LB1ItemData(base_item_id + 398),
    ItemName.dol_min10: LB1ItemData(base_item_id + 399),
}

hostage_item_table: Dict[str, LB1ItemData] = {
    ItemName.ycbob_host: LB1ItemData(base_item_id + 400, type="Hostage"),
    ItemName.air_host: LB1ItemData(base_item_id + 401, type="Hostage"),
    ItemName.apa_host: LB1ItemData(base_item_id + 402, type="Hostage"),
    ItemName.tfo_host: LB1ItemData(base_item_id + 403, type="Hostage"),
    ItemName.tsga_host: LB1ItemData(base_item_id + 404, type="Hostage"),
    ItemName.utc_host: LB1ItemData(base_item_id + 405, type="Hostage"),
    ItemName.zc_host: LB1ItemData(base_item_id + 406, type="Hostage"),
    ItemName.pl_host: LB1ItemData(base_item_id + 407, type="Hostage"),
    ItemName.jht_host: LB1ItemData(base_item_id + 408, type="Hostage"),
    ItemName.lfabt_host: LB1ItemData(base_item_id + 409, type="Hostage"),
    ItemName.itdn_host: LB1ItemData(base_item_id + 410, type="Hostage"),
    ItemName.tttot_host: LB1ItemData(base_item_id + 411, type="Hostage"),
    ItemName.trmaw_host: LB1ItemData(base_item_id + 412, type="Hostage"),
    ItemName.otr_host: LB1ItemData(base_item_id + 413, type="Hostage"),
    ItemName.gf_host: LB1ItemData(base_item_id + 414, type="Hostage"),
    ItemName.aet_host: LB1ItemData(base_item_id + 415, type="Hostage"),
    ItemName.bb_host: LB1ItemData(base_item_id + 416, type="Hostage"),
    ItemName.rtd_host: LB1ItemData(base_item_id + 417, type="Hostage"),
    ItemName.sts_host: LB1ItemData(base_item_id + 418, type="Hostage"),
    ItemName.adr_host: LB1ItemData(base_item_id + 419, type="Hostage"),
    ItemName.aw_host: LB1ItemData(base_item_id + 420, type="Hostage"),
    ItemName.asftc_host: LB1ItemData(base_item_id + 421, type="Hostage"),
    ItemName.tjm_host: LB1ItemData(base_item_id + 422, type="Hostage"),
    ItemName.tlotn_host: LB1ItemData(base_item_id + 423, type="Hostage"),
    ItemName.dol_host: LB1ItemData(base_item_id + 424, type="Hostage"),
}

level_unlocked_item_table: Dict[str, LB1ItemData] = {
    ItemName.ycbob_lvl: LB1ItemData(base_item_id + 425, ItemClassification.progression, "Level"),
    ItemName.air_lvl: LB1ItemData(base_item_id + 426, ItemClassification.progression, "Level"),
    ItemName.tfc_lvl: LB1ItemData(base_item_id + 427, ItemClassification.progression, "Level"),
    ItemName.apa_lvl: LB1ItemData(base_item_id + 428, ItemClassification.progression, "Level"),
    ItemName.tfo_lvl: LB1ItemData(base_item_id + 429, ItemClassification.progression, "Level"),
    ItemName.tsga_lvl: LB1ItemData(base_item_id + 430, ItemClassification.progression, "Level"),
    ItemName.bbb_lvl: LB1ItemData(base_item_id + 431, ItemClassification.progression, "Level"),
    ItemName.utc_lvl: LB1ItemData(base_item_id + 432, ItemClassification.progression, "Level"),
    ItemName.zc_lvl: LB1ItemData(base_item_id + 433, ItemClassification.progression, "Level"),
    ItemName.pl_lvl: LB1ItemData(base_item_id + 434, ItemClassification.progression, "Level"),
    ItemName.jht_lvl: LB1ItemData(base_item_id + 435, ItemClassification.progression, "Level"),
    ItemName.lfabt_lvl: LB1ItemData(base_item_id + 436, ItemClassification.progression, "Level"),
    ItemName.fotb_lvl: LB1ItemData(base_item_id + 437, ItemClassification.progression, "Level"),
    ItemName.itdn_lvl: LB1ItemData(base_item_id + 438, ItemClassification.progression, "Level"),
    ItemName.tttot_lvl: LB1ItemData(base_item_id + 439, ItemClassification.progression, "Level"),
    ItemName.trmaw_lvl: LB1ItemData(base_item_id + 440, ItemClassification.progression, "Level"),
    ItemName.otr_lvl: LB1ItemData(base_item_id + 441, ItemClassification.progression, "Level"),
    ItemName.gf_lvl: LB1ItemData(base_item_id + 442, ItemClassification.progression, "Level"),
    ItemName.aet_lvl: LB1ItemData(base_item_id + 443, ItemClassification.progression, "Level"),
    ItemName.bb_lvl: LB1ItemData(base_item_id + 444, ItemClassification.progression, "Level"),
    ItemName.rtd_lvl: LB1ItemData(base_item_id + 445, ItemClassification.progression, "Level"),
    ItemName.sts_lvl: LB1ItemData(base_item_id + 446, ItemClassification.progression, "Level"),
    ItemName.hag_lvl: LB1ItemData(base_item_id + 447, ItemClassification.progression, "Level"),
    ItemName.adr_lvl: LB1ItemData(base_item_id + 448, ItemClassification.progression, "Level"),
    ItemName.aw_lvl: LB1ItemData(base_item_id + 449, ItemClassification.progression, "Level"),
    ItemName.asftc_lvl: LB1ItemData(base_item_id + 450, ItemClassification.progression, "Level"),
    ItemName.bbpl_lvl: LB1ItemData(base_item_id + 451, ItemClassification.progression, "Level"),
    ItemName.tjm_lvl: LB1ItemData(base_item_id + 452, ItemClassification.progression, "Level"),
    ItemName.tlotn_lvl: LB1ItemData(base_item_id + 453, ItemClassification.progression, "Level"),
    ItemName.dol_lvl: LB1ItemData(base_item_id + 454, ItemClassification.progression, "Level"),
}

true_status_item_table: Dict[str, LB1ItemData] = {
    ItemName.ycbob_ts: LB1ItemData(base_item_id + 455, type="True Status"),
    ItemName.air_ts: LB1ItemData(base_item_id + 456, type="True Status"),
    ItemName.tfc_ts: LB1ItemData(base_item_id + 457, type="True Status"),
    ItemName.apa_ts: LB1ItemData(base_item_id + 458, type="True Status"),
    ItemName.tfo_ts: LB1ItemData(base_item_id + 459, type="True Status"),
    ItemName.tsga_ts: LB1ItemData(base_item_id + 460, type="True Status"),
    ItemName.bbb_ts: LB1ItemData(base_item_id + 461, type="True Status"),
    ItemName.utc_ts: LB1ItemData(base_item_id + 462, type="True Status"),
    ItemName.zc_ts: LB1ItemData(base_item_id + 463, type="True Status"),
    ItemName.pl_ts: LB1ItemData(base_item_id + 464, type="True Status"),
    ItemName.jht_ts: LB1ItemData(base_item_id + 465, type="True Status"),
    ItemName.lfabt_ts: LB1ItemData(base_item_id + 466, type="True Status"),
    ItemName.fotb_ts: LB1ItemData(base_item_id + 467, type="True Status"),
    ItemName.itdn_ts: LB1ItemData(base_item_id + 468, type="True Status"),
    ItemName.tttot_ts: LB1ItemData(base_item_id + 469, type="True Status"),
    ItemName.trmaw_ts: LB1ItemData(base_item_id + 470, type="True Status"),
    ItemName.otr_ts: LB1ItemData(base_item_id + 471, type="True Status"),
    ItemName.gf_ts: LB1ItemData(base_item_id + 472, type="True Status"),
    ItemName.aet_ts: LB1ItemData(base_item_id + 473, type="True Status"),
    ItemName.bb_ts: LB1ItemData(base_item_id + 474, type="True Status"),
    ItemName.rtd_ts: LB1ItemData(base_item_id + 475, type="True Status"),
    ItemName.sts_ts: LB1ItemData(base_item_id + 476, type="True Status"),
    ItemName.hag_ts: LB1ItemData(base_item_id + 477, type="True Status"),
    ItemName.adr_ts: LB1ItemData(base_item_id + 478, type="True Status"),
    ItemName.aw_ts: LB1ItemData(base_item_id + 479, type="True Status"),
    ItemName.asftc_ts: LB1ItemData(base_item_id + 480, type="True Status"),
    ItemName.bbpl_ts: LB1ItemData(base_item_id + 481, type="True Status"),
    ItemName.tjm_ts: LB1ItemData(base_item_id + 482, type="True Status"),
    ItemName.tlotn_ts: LB1ItemData(base_item_id + 483, type="True Status"),
    ItemName.dol_ts: LB1ItemData(base_item_id + 484, type="True Status"),
}

red_brick_item_table: Dict[str, LB1ItemData] = {
    ItemName.ycbob_rbc: LB1ItemData(base_item_id + 485, ItemClassification.progression, "Red Brick Collected"),
    ItemName.air_rbc: LB1ItemData(base_item_id + 486, ItemClassification.progression, "Red Brick Collected"),
    ItemName.tfc_rbc: LB1ItemData(base_item_id + 487, ItemClassification.progression, "Red Brick Collected"),
    ItemName.apa_rbc: LB1ItemData(base_item_id + 488, ItemClassification.progression, "Red Brick Collected"),
    ItemName.tfo_rbc: LB1ItemData(base_item_id + 489, ItemClassification.progression, "Red Brick Collected"),
    ItemName.tsga_rbc: LB1ItemData(base_item_id + 490, ItemClassification.progression, "Red Brick Collected"),
    ItemName.bbb_rbc: LB1ItemData(base_item_id + 491, ItemClassification.progression, "Red Brick Collected"),
    ItemName.utc_rbc: LB1ItemData(base_item_id + 492, ItemClassification.progression, "Red Brick Collected"),
    ItemName.zc_rbc: LB1ItemData(base_item_id + 493, ItemClassification.progression, "Red Brick Collected"),
    ItemName.pl_rbc: LB1ItemData(base_item_id + 494, ItemClassification.progression, "Red Brick Collected"),
    ItemName.jht_rbc: LB1ItemData(base_item_id + 495, ItemClassification.progression, "Red Brick Collected"),
    ItemName.lfabt_rbc: LB1ItemData(base_item_id + 496, ItemClassification.progression, "Red Brick Collected"),
    ItemName.fotb_rbc: LB1ItemData(base_item_id + 497, ItemClassification.progression, "Red Brick Collected"),
    ItemName.itdn_rbc: LB1ItemData(base_item_id + 498, ItemClassification.progression, "Red Brick Collected"),
    ItemName.tttot_rbc: LB1ItemData(base_item_id + 499, ItemClassification.progression, "Red Brick Collected"),
    ItemName.trmaw_rbc: LB1ItemData(base_item_id + 500, ItemClassification.progression, "Red Brick Collected"),
    ItemName.otr_rbc: LB1ItemData(base_item_id + 501, ItemClassification.progression, "Red Brick Collected"),
    ItemName.gf_rbc: LB1ItemData(base_item_id + 502, ItemClassification.progression, "Red Brick Collected"),
    ItemName.aet_rbc: LB1ItemData(base_item_id + 503, ItemClassification.progression, "Red Brick Collected"),
    ItemName.bb_rbc: LB1ItemData(base_item_id + 504, ItemClassification.progression, "Red Brick Collected"),
    ItemName.rtd_rbc: LB1ItemData(base_item_id + 505, ItemClassification.progression, "Red Brick Collected"),
    ItemName.sts_rbc: LB1ItemData(base_item_id + 506, ItemClassification.progression, "Red Brick Collected"),
    ItemName.hag_rbc: LB1ItemData(base_item_id + 507, ItemClassification.progression, "Red Brick Collected"),
    ItemName.adr_rbc: LB1ItemData(base_item_id + 508, ItemClassification.progression, "Red Brick Collected"),
    ItemName.aw_rbc: LB1ItemData(base_item_id + 509, ItemClassification.progression, "Red Brick Collected"),
    ItemName.asftc_rbc: LB1ItemData(base_item_id + 510, ItemClassification.progression, "Red Brick Collected"),
    ItemName.bbpl_rbc: LB1ItemData(base_item_id + 511, ItemClassification.progression, "Red Brick Collected"),
    ItemName.tjm_rbc: LB1ItemData(base_item_id + 512, ItemClassification.progression, "Red Brick Collected"),
    ItemName.tlotn_rbc: LB1ItemData(base_item_id + 513, ItemClassification.progression, "Red Brick Collected"),
    ItemName.dol_rbc: LB1ItemData(base_item_id + 514, ItemClassification.progression, "Red Brick Collected"),
}

red_brick_unlocked_table: Dict[str, LB1ItemData] = {
    ItemName.silhouettes_un: LB1ItemData(base_item_id + 515, ItemClassification.filler, "Red Brick Unlocked"),
    ItemName.beepbeep_un: LB1ItemData(base_item_id + 516, ItemClassification.filler, "Red Brick Unlocked"),
    ItemName.icerink_un: LB1ItemData(base_item_id + 517, ItemClassification.filler, "Red Brick Unlocked"),
    ItemName.disguise_un: LB1ItemData(base_item_id + 518, ItemClassification.filler, "Red Brick Unlocked"),
    ItemName.extratoggle_un: LB1ItemData(base_item_id + 519, ItemClassification.filler, "Red Brick Unlocked"),
    ItemName.scorex2_un: LB1ItemData(base_item_id + 520, ItemClassification.progression, "Red Brick Unlocked"),
    ItemName.scorex4_un: LB1ItemData(base_item_id + 521, ItemClassification.progression, "Red Brick Unlocked"),
    ItemName.scorex6_un: LB1ItemData(base_item_id + 522, ItemClassification.progression, "Red Brick Unlocked"),
    ItemName.scorex8_un: LB1ItemData(base_item_id + 523, ItemClassification.progression, "Red Brick Unlocked"),
    ItemName.scorex10_un: LB1ItemData(base_item_id + 524, ItemClassification.progression, "Red Brick Unlocked"),
    ItemName.studmagnet_un: LB1ItemData(base_item_id + 525, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.characterstuds_un: LB1ItemData(base_item_id + 526, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.minikitdetector_un: LB1ItemData(base_item_id + 527, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.powerbrickdetector_un: LB1ItemData(base_item_id + 528, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.alwaysscore_un: LB1ItemData(base_item_id + 529, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.fastbuild_un: LB1ItemData(base_item_id + 530, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.freezeshield_un: LB1ItemData(base_item_id + 531, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.regenhearts_un: LB1ItemData(base_item_id + 532, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.extrahearts_un: LB1ItemData(base_item_id + 533, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.invincibility_un: LB1ItemData(base_item_id + 534, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.fastgrapple_un: LB1ItemData(base_item_id + 535, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.fastbatarangs_un: LB1ItemData(base_item_id + 536, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.moretargets_un: LB1ItemData(base_item_id + 537, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.flamingbatarang_un: LB1ItemData(base_item_id + 538, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.slam_un: LB1ItemData(base_item_id + 539, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.moredetonators_un: LB1ItemData(base_item_id + 540, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.armourplating_un: LB1ItemData(base_item_id + 541, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.sonicpain_un: LB1ItemData(base_item_id + 542, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.areaeffect_un: LB1ItemData(base_item_id + 543, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.bats_un: LB1ItemData(base_item_id + 544, ItemClassification.filler, "Red Brick Unlocked"),
    ItemName.freezebatarang_un: LB1ItemData(base_item_id + 545, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.decoy_un: LB1ItemData(base_item_id + 546, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.fastwalk_un: LB1ItemData(base_item_id + 547, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.fasterpieces_un: LB1ItemData(base_item_id + 548, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.piecedetector_un: LB1ItemData(base_item_id + 549, ItemClassification.useful, "Red Brick Unlocked"),
}

character_token_received_table: Dict[str, LB1ItemData] = {
    # ItemName.batman_token: LB1ItemData(base_item_id + 550, ItemClassification.progression, "Token"),
    # ItemName.robin_token: LB1ItemData(base_item_id + 551, ItemClassification.progression, "Token"),
    ItemName.brucewayne_token: LB1ItemData(base_item_id + 552, ItemClassification.progression, "Token"),
    ItemName.alfred_token: LB1ItemData(base_item_id + 553, ItemClassification.progression, "Token"),
    ItemName.batgirl_token: LB1ItemData(base_item_id + 554, ItemClassification.progression, "Token"),
    ItemName.nightwing_token: LB1ItemData(base_item_id + 555, ItemClassification.progression, "Token"),
    ItemName.commissionergordon_token: LB1ItemData(base_item_id + 556, ItemClassification.progression, "Token"),
    ItemName.policeofficer_token: LB1ItemData(base_item_id + 557, ItemClassification.progression, "Token"),
    ItemName.fishmonger_token: LB1ItemData(base_item_id + 558, ItemClassification.progression, "Token"),
    ItemName.militarypoliceman_token: LB1ItemData(base_item_id + 559, ItemClassification.progression, "Token"),
    ItemName.securityguard_token: LB1ItemData(base_item_id + 560, ItemClassification.progression, "Token"),
    ItemName.swat_token: LB1ItemData(base_item_id + 561, ItemClassification.progression, "Token"),
    ItemName.scientist_token: LB1ItemData(base_item_id + 562, ItemClassification.progression, "Token"),
    ItemName.sailor_token: LB1ItemData(base_item_id + 563, ItemClassification.progression, "Token"),
    ItemName.policemarksman_token: LB1ItemData(base_item_id + 564, ItemClassification.progression, "Token"),
    # ItemName.clayface_token: LB1ItemData(base_item_id + 565, ItemClassification.progression, "Token"),
    # ItemName.mrfreeze_token: LB1ItemData(base_item_id + 566, ItemClassification.progression, "Token"),
    # ItemName.poisonivy_token: LB1ItemData(base_item_id + 567, ItemClassification.progression, "Token"),
    # ItemName.twoface_token: LB1ItemData(base_item_id + 568, ItemClassification.progression, "Token"),
    # ItemName.riddler_token: LB1ItemData(base_item_id + 569, ItemClassification.progression, "Token"),
    # ItemName.bane_token: LB1ItemData(base_item_id + 570, ItemClassification.progression, "Token"),
    # ItemName.catwoman_token: LB1ItemData(base_item_id + 571, ItemClassification.progression, "Token"),
    ItemName.catwomanclassic_token: LB1ItemData(base_item_id + 572, ItemClassification.progression, "Token"),
    # ItemName.killercroc_token: LB1ItemData(base_item_id + 573, ItemClassification.progression, "Token"),
    ItemName.manbat_token: LB1ItemData(base_item_id + 574, ItemClassification.progression, "Token"),
    # ItemName.penguin_token: LB1ItemData(base_item_id + 575, ItemClassification.progression, "Token"),
    # ItemName.harleyquinn_token: LB1ItemData(base_item_id + 576, ItemClassification.progression, "Token"),
    # ItemName.scarecrow_token: LB1ItemData(base_item_id + 577, ItemClassification.progression, "Token"),
    # ItemName.killermoth_token: LB1ItemData(base_item_id + 578, ItemClassification.progression, "Token"),
    ItemName.madhatter_token: LB1ItemData(base_item_id + 579, ItemClassification.progression, "Token"),
    # ItemName.joker_token: LB1ItemData(base_item_id + 580, ItemClassification.progression, "Token"),
    ItemName.jokertropical_token: LB1ItemData(base_item_id + 581, ItemClassification.progression, "Token"),
    ItemName.poisonivygoon_token: LB1ItemData(base_item_id + 582, ItemClassification.progression, "Token"),
    ItemName.zoosweeper_token: LB1ItemData(base_item_id + 583, ItemClassification.progression, "Token"),
    ItemName.freezegirl_token: LB1ItemData(base_item_id + 584, ItemClassification.progression, "Token"),
    ItemName.yeti_token: LB1ItemData(base_item_id + 585, ItemClassification.progression, "Token"),
    ItemName.riddlergoon_token: LB1ItemData(base_item_id + 586, ItemClassification.progression, "Token"),
    ItemName.riddlerhenchman_token: LB1ItemData(base_item_id + 587, ItemClassification.progression, "Token"),
    ItemName.penguingoon_token: LB1ItemData(base_item_id + 588, ItemClassification.progression, "Token"),
    ItemName.penguinhenchman_token: LB1ItemData(base_item_id + 589, ItemClassification.progression, "Token"),
    ItemName.penguinminion_token: LB1ItemData(base_item_id + 590, ItemClassification.progression, "Token"),
    ItemName.jokergoon_token: LB1ItemData(base_item_id + 591, ItemClassification.progression, "Token"),
    ItemName.jokerhenchman_token: LB1ItemData(base_item_id + 592, ItemClassification.progression, "Token"),
    ItemName.clowngoon_token: LB1ItemData(base_item_id + 593, ItemClassification.progression, "Token"),
    ItemName.hush_token: LB1ItemData(base_item_id + 594, ItemClassification.progression, "Hard Token"),
    ItemName.rasalghul_token: LB1ItemData(base_item_id + 595, ItemClassification.progression, "Hard Token"),
    # ItemName.hero1_token: LB1ItemData(base_item_id + 596, ItemClassification.progression, "Token"),
    # ItemName.hero2_token: LB1ItemData(base_item_id + 597, ItemClassification.progression, "Token"),
    # ItemName.batmobile_token: LB1ItemData(base_item_id + 598, ItemClassification.progression, "Token"),
    # ItemName.batcycle_token: LB1ItemData(base_item_id + 599, ItemClassification.progression, "Token"),
    ItemName.policecar_token: LB1ItemData(base_item_id + 600, ItemClassification.progression, "Token"),
    ItemName.policebike_token: LB1ItemData(base_item_id + 601, ItemClassification.progression, "Token"),
    ItemName.policevan_token: LB1ItemData(base_item_id + 602, ItemClassification.progression, "Token"),
    ItemName.battank_token: LB1ItemData(base_item_id + 603, ItemClassification.progression, "Token"),
    ItemName.catmotorcycle_token: LB1ItemData(base_item_id + 604, ItemClassification.progression, "Token"),
    ItemName.armouredtruck_token: LB1ItemData(base_item_id + 605, ItemClassification.progression, "Token"),
    ItemName.freezekart_token: LB1ItemData(base_item_id + 606, ItemClassification.progression, "Token"),
    ItemName.hammertruck_token: LB1ItemData(base_item_id + 607, ItemClassification.progression, "Token"),
    ItemName.jokervan_token: LB1ItemData(base_item_id + 608, ItemClassification.progression, "Token"),
    ItemName.garbagetruck_token: LB1ItemData(base_item_id + 609, ItemClassification.progression, "Token"),
    # ItemName.batboat_token: LB1ItemData(base_item_id + 610, ItemClassification.progression, "Token"),
    # ItemName.robinswatercraft_token: LB1ItemData(base_item_id + 611, ItemClassification.progression, "Token"),
    ItemName.robinssubmarine_token: LB1ItemData(base_item_id + 612, ItemClassification.progression, "Token"),
    ItemName.policewatercraft_token: LB1ItemData(base_item_id + 613, ItemClassification.progression, "Token"),
    ItemName.policeboat_token: LB1ItemData(base_item_id + 614, ItemClassification.progression, "Token"),
    # ItemName.penguinsubmarine_token: LB1ItemData(base_item_id + 615, ItemClassification.progression, "Token"),
    # ItemName.swamprider_token: LB1ItemData(base_item_id + 616, ItemClassification.progression, "Token"),
    ItemName.penguingoonsub_token: LB1ItemData(base_item_id + 617, ItemClassification.progression, "Token"),
    ItemName.iceberg_token: LB1ItemData(base_item_id + 618, ItemClassification.progression, "Token"),
    ItemName.steamboat_token: LB1ItemData(base_item_id + 619, ItemClassification.progression, "Token"),
    # ItemName.batwing_token: LB1ItemData(base_item_id + 620, ItemClassification.progression, "Token"),
    # ItemName.batcopter_token: LB1ItemData(base_item_id + 621, ItemClassification.progression, "Token"),
    ItemName.harbourhelicopter_token: LB1ItemData(base_item_id + 622, ItemClassification.progression, "Token"),
    ItemName.policehelicopter_token: LB1ItemData(base_item_id + 623, ItemClassification.progression, "Token"),
    ItemName.privatejet_token: LB1ItemData(base_item_id + 624, ItemClassification.progression, "Token"),
    # ItemName.jokerhelicopter_token: LB1ItemData(base_item_id + 625, ItemClassification.progression, "Token"),
    # ItemName.scarecrowbiplane_token: LB1ItemData(base_item_id + 626, ItemClassification.progression, "Token"),
    ItemName.goonhelicopter_token: LB1ItemData(base_item_id + 627, ItemClassification.progression, "Token"),
    ItemName.riddlerjet_token: LB1ItemData(base_item_id + 628, ItemClassification.progression, "Token"),
    ItemName.glider_token: LB1ItemData(base_item_id + 629, ItemClassification.progression, "Token"),
}

all_item_table = {
    **character_item_table,
    # **hard_character_item_table,
    # **suit_item_table,
    **minikit_item_table,
    **hostage_item_table,
    **level_unlocked_item_table,
    **true_status_item_table,
    **red_brick_item_table,
    **red_brick_unlocked_table,
    **character_token_received_table,
    **filler_item_table,
}

minikit_names_set = set(minikit_item_table.keys())
hostage_names_set = set(hostage_item_table.keys())

# event_item_table: Dict[str, LB1ItemData] = {
#     # "Completed Wayne Manor": LB1ItemData(None, classification=ItemClassification.progression),
#     # "Completed Arkham Asylum": LB1ItemData(None, classification=ItemClassification.progression),
#     # "Completed All Levels": LB1ItemData(None, classification=ItemClassification.progression),
#     "Obtain Minikit Goal": LB1ItemData(None, classification=ItemClassification.progression),
#     # "Hush": LB1ItemData(None, classification=ItemClassification.progression),
#     # "Ra Sha Guul": LB1ItemData(None, classification=ItemClassification.progression),
# }
