from typing import Dict, NamedTuple

from BaseClasses import Location
from .Options import LB1Options
from .Names import LocationName, RegionName


class LB1Location(Location):
    game: str = "Lego Batman The Videogame"


class LocationData(NamedTuple):
    id: int = 0
    region: str = ""
    price: int = 0


base_location_id: int = 400000

character_location_table: Dict[str, LocationData] = {
    # LocationName.batman_unlocked: LocationData(base_location_id + 0, RegionName.bc),
    # LocationName.robin_unlocked: LocationData(base_location_id + 1, RegionName.bc),
    LocationName.brucewayne_unlocked: LocationData(base_location_id + 2, RegionName.sh, 100000),
    LocationName.alfred_unlocked: LocationData(base_location_id + 3, RegionName.sh, 75000),
    LocationName.batgirl_unlocked: LocationData(base_location_id + 4, RegionName.sh, 100000),
    LocationName.nightwing_unlocked: LocationData(base_location_id + 5, RegionName.sh, 125000),
    LocationName.commissionergordon_unlocked: LocationData(base_location_id + 6, RegionName.sh, 25000),
    LocationName.policeofficer_unlocked: LocationData(base_location_id + 7, RegionName.sh, 5000),
    LocationName.fishmonger_unlocked: LocationData(base_location_id + 8, RegionName.sh, 4000),
    LocationName.militarypoliceman_unlocked: LocationData(base_location_id + 9, RegionName.sh, 17000),
    LocationName.securityguard_unlocked: LocationData(base_location_id + 10, RegionName.sh, 10000),
    LocationName.swat_unlocked: LocationData(base_location_id + 11, RegionName.sh, 10000),
    LocationName.scientist_unlocked: LocationData(base_location_id + 12, RegionName.sh, 6000),
    LocationName.sailor_unlocked: LocationData(base_location_id + 13, RegionName.sh, 5000),
    LocationName.policemarksman_unlocked: LocationData(base_location_id + 14, RegionName.sh, 5000),
    LocationName.clayface_unlocked: LocationData(base_location_id + 15, RegionName.trmaw),
    LocationName.mrfreeze_unlocked: LocationData(base_location_id + 16, RegionName.otr),
    LocationName.poisonivy_unlocked: LocationData(base_location_id + 17, RegionName.gf),
    LocationName.twoface_unlocked: LocationData(base_location_id + 18, RegionName.aa),
    LocationName.riddler_unlocked: LocationData(base_location_id + 19, RegionName.aa),
    LocationName.bane_unlocked: LocationData(base_location_id + 20, RegionName.rtd),
    LocationName.catwoman_unlocked: LocationData(base_location_id + 21, RegionName.aa),
    LocationName.catwomanclassic_unlocked: LocationData(base_location_id + 22, RegionName.sh, 67000),
    LocationName.killercroc_unlocked: LocationData(base_location_id + 23, RegionName.adr),
    LocationName.manbat_unlocked: LocationData(base_location_id + 24, RegionName.sh, 40000),
    LocationName.penguin_unlocked: LocationData(base_location_id + 25, RegionName.aa),
    LocationName.harleyquinn_unlocked: LocationData(base_location_id + 26, RegionName.aa),
    LocationName.scarecrow_unlocked: LocationData(base_location_id + 27, RegionName.tjm),
    LocationName.killermoth_unlocked: LocationData(base_location_id + 28, RegionName.tlotn),
    LocationName.madhatter_unlocked: LocationData(base_location_id + 29, RegionName.sh, 35000),
    LocationName.joker_unlocked: LocationData(base_location_id + 30, RegionName.aa),
    LocationName.jokertropical_unlocked: LocationData(base_location_id + 31, RegionName.sh, 30000),
    LocationName.poisonivygoon_unlocked: LocationData(base_location_id + 32, RegionName.sh, 25000),
    LocationName.zoosweeper_unlocked: LocationData(base_location_id + 33, RegionName.sh, 12500),
    LocationName.freezegirl_unlocked: LocationData(base_location_id + 34, RegionName.sh, 4000),
    LocationName.yeti_unlocked: LocationData(base_location_id + 35, RegionName.sh, 9000),
    LocationName.riddlergoon_unlocked: LocationData(base_location_id + 36, RegionName.sh, 6000),
    LocationName.riddlerhenchman_unlocked: LocationData(base_location_id + 37, RegionName.sh, 7000),
    LocationName.penguingoon_unlocked: LocationData(base_location_id + 38, RegionName.sh, 3000),
    LocationName.penguinhenchman_unlocked: LocationData(base_location_id + 39, RegionName.sh, 5000),
    LocationName.penguinminion_unlocked: LocationData(base_location_id + 40, RegionName.sh, 30000),
    LocationName.jokergoon_unlocked: LocationData(base_location_id + 41, RegionName.sh, 7000),
    LocationName.jokerhenchman_unlocked: LocationData(base_location_id + 42, RegionName.sh, 9000),
    LocationName.clowngoon_unlocked: LocationData(base_location_id + 43, RegionName.sh, 100000),
    # Hush
    # Ras
    # LocationName.hero1_unlocked: LocationData(base_location_id + 46, RegionName.sh),
    # LocationName.hero2_unlocked: LocationData(base_location_id + 47, RegionName.sh),
    LocationName.batmobile_unlocked: LocationData(base_location_id + 48, RegionName.tfc),
    LocationName.batcycle_unlocked: LocationData(base_location_id + 49, RegionName.tfc),
    LocationName.policecar_unlocked: LocationData(base_location_id + 50, RegionName.sh, 10000),
    LocationName.policebike_unlocked: LocationData(base_location_id + 51, RegionName.sh, 11000),
    LocationName.policevan_unlocked: LocationData(base_location_id + 52, RegionName.sh, 13000),
    LocationName.battank_unlocked: LocationData(base_location_id + 53, RegionName.sh, 200000),
    LocationName.catmotorcycle_unlocked: LocationData(base_location_id + 54, RegionName.sh, 23000),
    LocationName.armouredtruck_unlocked: LocationData(base_location_id + 55, RegionName.sh, 24000),
    LocationName.freezekart_unlocked: LocationData(base_location_id + 56, RegionName.sh, 25000),
    LocationName.hammertruck_unlocked: LocationData(base_location_id + 57, RegionName.sh, 80000),
    LocationName.jokervan_unlocked: LocationData(base_location_id + 58, RegionName.sh, 60000),
    LocationName.garbagetruck_unlocked: LocationData(base_location_id + 59, RegionName.sh, 99000),
    LocationName.batboat_unlocked: LocationData(base_location_id + 60, RegionName.bbb),
    LocationName.robinswatercraft_unlocked: LocationData(base_location_id + 61, RegionName.bbb),
    LocationName.robinssubmarine_unlocked: LocationData(base_location_id + 62, RegionName.sh, 30000),
    LocationName.policewatercraft_unlocked: LocationData(base_location_id + 63, RegionName.sh, 12000),
    LocationName.policeboat_unlocked: LocationData(base_location_id + 64, RegionName.sh, 13000),
    LocationName.penguinsubmarine_unlocked: LocationData(base_location_id + 65, RegionName.hag),
    LocationName.swamprider_unlocked: LocationData(base_location_id + 66, RegionName.hag),
    LocationName.penguingoonsub_unlocked: LocationData(base_location_id + 67, RegionName.sh, 15000),
    LocationName.iceberg_unlocked: LocationData(base_location_id + 68, RegionName.sh, 23000),
    LocationName.steamboat_unlocked: LocationData(base_location_id + 69, RegionName.sh, 23000),
    LocationName.batwing_unlocked: LocationData(base_location_id + 70, RegionName.fotb),
    LocationName.batcopter_unlocked: LocationData(base_location_id + 71, RegionName.fotb),
    LocationName.harbourhelicopter_unlocked: LocationData(base_location_id + 72, RegionName.sh, 16000),
    LocationName.policehelicopter_unlocked: LocationData(base_location_id + 73, RegionName.sh, 14000),
    LocationName.privatejet_unlocked: LocationData(base_location_id + 74, RegionName.sh, 15000),
    LocationName.jokerhelicopter_unlocked: LocationData(base_location_id + 75, RegionName.bbpl),
    LocationName.scarecrowbiplane_unlocked: LocationData(base_location_id + 76, RegionName.bbpl),
    LocationName.goonhelicopter_unlocked: LocationData(base_location_id + 77, RegionName.sh, 11000),
    LocationName.riddlerjet_unlocked: LocationData(base_location_id + 78, RegionName.sh, 17000),
    LocationName.glider_unlocked: LocationData(base_location_id + 79, RegionName.sh, 18000),
}

hard_character_location_table: Dict[str, LocationData] = {
    LocationName.hush_unlocked: LocationData(base_location_id + 44, RegionName.sh, 150000),
    LocationName.rasalghul_unlocked: LocationData(base_location_id + 45, RegionName.sh, 500000),
}

# Currently stored in Batcave because it is sounding like they can be unlocked in multiple levels
# suit_location_table: Dict[str, LocationData] = {
#     # LocationName.batsuit_collected: LocationData(base_location_id + 80, RegionName.bc),
#     LocationName.heatprotectsuit: LocationData(base_location_id + 81, RegionName.apa),
#     LocationName.glidesuit: LocationData(base_location_id + 82, RegionName.bc),
#     LocationName.demosuit: LocationData(base_location_id + 83, RegionName.bc),
#     LocationName.sonicsuit: LocationData(base_location_id + 84, RegionName.bc),
#     # LocationName.robinsuit_collected: LocationData(base_location_id + 85, RegionName.bc),
#     LocationName.watersuit: LocationData(base_location_id + 86, RegionName.bc),
#     LocationName.techsuit: LocationData(base_location_id + 87, RegionName.bc),
#     LocationName.magsuit: LocationData(base_location_id + 88, RegionName.bc),
#     LocationName.attractsuit: LocationData(base_location_id + 89, RegionName.bc),
# }

minikit_location_table: Dict[str, LocationData] = {
    # You can Bank on Batman
    LocationName.ycbob_min1: LocationData(base_location_id + 100, RegionName.ycbob),
    LocationName.ycbob_min2: LocationData(base_location_id + 101, RegionName.ycbob),
    LocationName.ycbob_min3: LocationData(base_location_id + 102, RegionName.ycbob),
    LocationName.ycbob_min4: LocationData(base_location_id + 103, RegionName.ycbob),
    LocationName.ycbob_min5: LocationData(base_location_id + 104, RegionName.ycbobf),
    LocationName.ycbob_min6: LocationData(base_location_id + 105, RegionName.ycbobf),
    LocationName.ycbob_min7: LocationData(base_location_id + 106, RegionName.ycbobf),
    LocationName.ycbob_min8: LocationData(base_location_id + 107, RegionName.ycbobf),
    LocationName.ycbob_min9: LocationData(base_location_id + 108, RegionName.ycbobf),
    LocationName.ycbob_min10: LocationData(base_location_id + 109, RegionName.ycbobf),

    # An Icy Reception
    LocationName.air_min1: LocationData(base_location_id + 110, RegionName.air),
    LocationName.air_min2: LocationData(base_location_id + 111, RegionName.air),
    LocationName.air_min3: LocationData(base_location_id + 112, RegionName.air),
    LocationName.air_min4: LocationData(base_location_id + 113, RegionName.air),
    LocationName.air_min5: LocationData(base_location_id + 114, RegionName.air),
    LocationName.air_min6: LocationData(base_location_id + 115, RegionName.air),
    LocationName.air_min7: LocationData(base_location_id + 116, RegionName.airf),
    LocationName.air_min8: LocationData(base_location_id + 117, RegionName.airf),
    LocationName.air_min9: LocationData(base_location_id + 118, RegionName.airf),
    LocationName.air_min10: LocationData(base_location_id + 119, RegionName.airf),
    # Two-Face Chase
    LocationName.tfc_min1: LocationData(base_location_id + 120, RegionName.tfc),
    LocationName.tfc_min2: LocationData(base_location_id + 121, RegionName.tfc),
    LocationName.tfc_min3: LocationData(base_location_id + 122, RegionName.tfc),
    LocationName.tfc_min4: LocationData(base_location_id + 123, RegionName.tfc),
    LocationName.tfc_min5: LocationData(base_location_id + 124, RegionName.tfc),
    LocationName.tfc_min6: LocationData(base_location_id + 125, RegionName.tfc),
    LocationName.tfc_min7: LocationData(base_location_id + 126, RegionName.tfcf),
    LocationName.tfc_min8: LocationData(base_location_id + 127, RegionName.tfcf),
    LocationName.tfc_min9: LocationData(base_location_id + 128, RegionName.tfc),
    LocationName.tfc_min10: LocationData(base_location_id + 129, RegionName.tfcf),
    # A Poisonous Appointment
    LocationName.apa_min1: LocationData(base_location_id + 130, RegionName.apa),
    LocationName.apa_min2: LocationData(base_location_id + 131, RegionName.apa),
    LocationName.apa_min3: LocationData(base_location_id + 132, RegionName.apa),
    LocationName.apa_min4: LocationData(base_location_id + 133, RegionName.apa),
    LocationName.apa_min5: LocationData(base_location_id + 134, RegionName.apa),
    LocationName.apa_min6: LocationData(base_location_id + 135, RegionName.apaf),
    LocationName.apa_min7: LocationData(base_location_id + 136, RegionName.apaf),
    LocationName.apa_min8: LocationData(base_location_id + 137, RegionName.apaf),
    LocationName.apa_min9: LocationData(base_location_id + 138, RegionName.apaf),
    LocationName.apa_min10: LocationData(base_location_id + 139, RegionName.apaf),
    # The Face-Off
    LocationName.tfo_min1: LocationData(base_location_id + 140, RegionName.tfo),
    LocationName.tfo_min2: LocationData(base_location_id + 141, RegionName.tfo),
    LocationName.tfo_min3: LocationData(base_location_id + 142, RegionName.tfo),
    LocationName.tfo_min4: LocationData(base_location_id + 143, RegionName.tfo),
    LocationName.tfo_min5: LocationData(base_location_id + 144, RegionName.tfo),
    LocationName.tfo_min6: LocationData(base_location_id + 145, RegionName.tfof),
    LocationName.tfo_min7: LocationData(base_location_id + 146, RegionName.tfof),
    LocationName.tfo_min8: LocationData(base_location_id + 147, RegionName.tfof),
    LocationName.tfo_min9: LocationData(base_location_id + 148, RegionName.tfof),
    LocationName.tfo_min10: LocationData(base_location_id + 149, RegionName.tfof),
    # There She Goes Again
    LocationName.tsga_min1: LocationData(base_location_id + 150, RegionName.tsga),
    LocationName.tsga_min2: LocationData(base_location_id + 151, RegionName.tsga),
    LocationName.tsga_min3: LocationData(base_location_id + 152, RegionName.tsga),
    LocationName.tsga_min4: LocationData(base_location_id + 153, RegionName.tsga),
    LocationName.tsga_min5: LocationData(base_location_id + 154, RegionName.tsga),
    LocationName.tsga_min6: LocationData(base_location_id + 155, RegionName.tsgaf),
    LocationName.tsga_min7: LocationData(base_location_id + 156, RegionName.tsgaf),
    LocationName.tsga_min8: LocationData(base_location_id + 157, RegionName.tsgaf),
    LocationName.tsga_min9: LocationData(base_location_id + 158, RegionName.tsgaf),
    LocationName.tsga_min10: LocationData(base_location_id + 159, RegionName.tsgaf),
    # Batboat Battle
    LocationName.bbb_min1: LocationData(base_location_id + 160, RegionName.bbb),
    LocationName.bbb_min2: LocationData(base_location_id + 161, RegionName.bbb),
    LocationName.bbb_min3: LocationData(base_location_id + 162, RegionName.bbbf),
    LocationName.bbb_min4: LocationData(base_location_id + 163, RegionName.bbb),
    LocationName.bbb_min5: LocationData(base_location_id + 164, RegionName.bbbf),
    LocationName.bbb_min6: LocationData(base_location_id + 165, RegionName.bbbf),
    LocationName.bbb_min7: LocationData(base_location_id + 166, RegionName.bbb),
    LocationName.bbb_min8: LocationData(base_location_id + 167, RegionName.bbb),
    LocationName.bbb_min9: LocationData(base_location_id + 168, RegionName.bbbf),
    LocationName.bbb_min10: LocationData(base_location_id + 169, RegionName.bbbf),
    # Under the City
    LocationName.utc_min1: LocationData(base_location_id + 170, RegionName.utc),
    LocationName.utc_min2: LocationData(base_location_id + 171, RegionName.utc),
    LocationName.utc_min3: LocationData(base_location_id + 172, RegionName.utc),
    LocationName.utc_min4: LocationData(base_location_id + 173, RegionName.utc),
    LocationName.utc_min5: LocationData(base_location_id + 174, RegionName.utcf),
    LocationName.utc_min6: LocationData(base_location_id + 175, RegionName.utcf),
    LocationName.utc_min7: LocationData(base_location_id + 176, RegionName.utcf),
    LocationName.utc_min8: LocationData(base_location_id + 177, RegionName.utcf),
    LocationName.utc_min9: LocationData(base_location_id + 178, RegionName.utcf),
    LocationName.utc_min10: LocationData(base_location_id + 179, RegionName.utcf),
    # Zoo's Company
    LocationName.zc_min1: LocationData(base_location_id + 180, RegionName.zc),
    LocationName.zc_min2: LocationData(base_location_id + 181, RegionName.zc),
    LocationName.zc_min3: LocationData(base_location_id + 182, RegionName.zc),
    LocationName.zc_min4: LocationData(base_location_id + 183, RegionName.zc),
    LocationName.zc_min5: LocationData(base_location_id + 184, RegionName.zcf),
    LocationName.zc_min6: LocationData(base_location_id + 185, RegionName.zcf),
    LocationName.zc_min7: LocationData(base_location_id + 186, RegionName.zcf),
    LocationName.zc_min8: LocationData(base_location_id + 187, RegionName.zcf),
    LocationName.zc_min9: LocationData(base_location_id + 188, RegionName.zcf),
    LocationName.zc_min10: LocationData(base_location_id + 189, RegionName.zcf),
    # Penguin's Lair
    LocationName.pl_min1: LocationData(base_location_id + 190, RegionName.pl),
    LocationName.pl_min2: LocationData(base_location_id + 191, RegionName.pl),
    LocationName.pl_min3: LocationData(base_location_id + 192, RegionName.pl),
    LocationName.pl_min4: LocationData(base_location_id + 193, RegionName.plf),
    LocationName.pl_min5: LocationData(base_location_id + 194, RegionName.pl),
    LocationName.pl_min6: LocationData(base_location_id + 195, RegionName.plf),
    LocationName.pl_min7: LocationData(base_location_id + 196, RegionName.plf),
    LocationName.pl_min8: LocationData(base_location_id + 197, RegionName.plf),
    LocationName.pl_min9: LocationData(base_location_id + 198, RegionName.plf),
    LocationName.pl_min10: LocationData(base_location_id + 199, RegionName.plf),
    # Joker's Home Turf
    LocationName.jht_min1: LocationData(base_location_id + 200, RegionName.jht),
    LocationName.jht_min2: LocationData(base_location_id + 201, RegionName.jht),
    LocationName.jht_min3: LocationData(base_location_id + 202, RegionName.jht),
    LocationName.jht_min4: LocationData(base_location_id + 203, RegionName.jht),
    LocationName.jht_min5: LocationData(base_location_id + 204, RegionName.jht),
    LocationName.jht_min6: LocationData(base_location_id + 205, RegionName.jht),
    LocationName.jht_min7: LocationData(base_location_id + 206, RegionName.jht),
    LocationName.jht_min8: LocationData(base_location_id + 207, RegionName.jht),
    LocationName.jht_min9: LocationData(base_location_id + 208, RegionName.jht),
    LocationName.jht_min10: LocationData(base_location_id + 209, RegionName.jht),
    # Little Fun at the Big Top
    LocationName.lfabt_min1: LocationData(base_location_id + 210, RegionName.lfabt),
    LocationName.lfabt_min2: LocationData(base_location_id + 211, RegionName.lfabt),
    LocationName.lfabt_min3: LocationData(base_location_id + 212, RegionName.lfabtf),
    LocationName.lfabt_min4: LocationData(base_location_id + 213, RegionName.lfabt),
    LocationName.lfabt_min5: LocationData(base_location_id + 214, RegionName.lfabtf),
    LocationName.lfabt_min6: LocationData(base_location_id + 215, RegionName.lfabtf),
    LocationName.lfabt_min7: LocationData(base_location_id + 216, RegionName.lfabtf),
    LocationName.lfabt_min8: LocationData(base_location_id + 217, RegionName.lfabtf),
    LocationName.lfabt_min9: LocationData(base_location_id + 218, RegionName.lfabtf),
    LocationName.lfabt_min10: LocationData(base_location_id + 219, RegionName.lfabtf),
    # Flight of the Bat
    LocationName.fotb_min1: LocationData(base_location_id + 220, RegionName.fotb),
    LocationName.fotb_min2: LocationData(base_location_id + 221, RegionName.fotb),
    LocationName.fotb_min3: LocationData(base_location_id + 222, RegionName.fotb),
    LocationName.fotb_min4: LocationData(base_location_id + 223, RegionName.fotb),
    LocationName.fotb_min5: LocationData(base_location_id + 224, RegionName.fotb),
    LocationName.fotb_min6: LocationData(base_location_id + 225, RegionName.fotb),
    LocationName.fotb_min7: LocationData(base_location_id + 226, RegionName.fotb),
    LocationName.fotb_min8: LocationData(base_location_id + 227, RegionName.fotb),
    LocationName.fotb_min9: LocationData(base_location_id + 228, RegionName.fotb),
    LocationName.fotb_min10: LocationData(base_location_id + 229, RegionName.fotb),
    # In the Dark Night
    LocationName.itdn_min1: LocationData(base_location_id + 230, RegionName.itdn),
    LocationName.itdn_min2: LocationData(base_location_id + 231, RegionName.itdn),
    LocationName.itdn_min3: LocationData(base_location_id + 232, RegionName.itdn),
    LocationName.itdn_min4: LocationData(base_location_id + 233, RegionName.itdnf),
    LocationName.itdn_min5: LocationData(base_location_id + 234, RegionName.itdnf),
    LocationName.itdn_min6: LocationData(base_location_id + 235, RegionName.itdnf),
    LocationName.itdn_min7: LocationData(base_location_id + 236, RegionName.itdnf),
    LocationName.itdn_min8: LocationData(base_location_id + 237, RegionName.itdnf),
    LocationName.itdn_min9: LocationData(base_location_id + 238, RegionName.itdnf),
    LocationName.itdn_min10: LocationData(base_location_id + 239, RegionName.itdn),
    # To the Top of the Tower
    LocationName.tttot_min1: LocationData(base_location_id + 240, RegionName.tttotf),
    LocationName.tttot_min2: LocationData(base_location_id + 241, RegionName.tttot),
    LocationName.tttot_min3: LocationData(base_location_id + 242, RegionName.tttotf),
    LocationName.tttot_min4: LocationData(base_location_id + 243, RegionName.tttot),
    LocationName.tttot_min5: LocationData(base_location_id + 244, RegionName.tttotf),
    LocationName.tttot_min6: LocationData(base_location_id + 245, RegionName.tttotf),
    LocationName.tttot_min7: LocationData(base_location_id + 246, RegionName.tttotf),
    LocationName.tttot_min8: LocationData(base_location_id + 247, RegionName.tttotf),
    LocationName.tttot_min9: LocationData(base_location_id + 248, RegionName.tttotf),
    LocationName.tttot_min10: LocationData(base_location_id + 249, RegionName.tttotf),
    # The Riddler Makes a Withdrawal
    LocationName.trmaw_min1: LocationData(base_location_id + 250, RegionName.trmaw),
    LocationName.trmaw_min2: LocationData(base_location_id + 251, RegionName.trmaw),
    LocationName.trmaw_min3: LocationData(base_location_id + 252, RegionName.trmaw),
    LocationName.trmaw_min4: LocationData(base_location_id + 253, RegionName.trmawf),
    LocationName.trmaw_min5: LocationData(base_location_id + 254, RegionName.trmawf),
    LocationName.trmaw_min6: LocationData(base_location_id + 255, RegionName.trmawf),
    LocationName.trmaw_min7: LocationData(base_location_id + 256, RegionName.trmaw),
    LocationName.trmaw_min8: LocationData(base_location_id + 257, RegionName.trmaw),
    LocationName.trmaw_min9: LocationData(base_location_id + 258, RegionName.trmawf),
    LocationName.trmaw_min10: LocationData(base_location_id + 259, RegionName.trmaw),
    # On the Rocks
    LocationName.otr_min1: LocationData(base_location_id + 260, RegionName.otr),
    LocationName.otr_min2: LocationData(base_location_id + 261, RegionName.otr),
    LocationName.otr_min3: LocationData(base_location_id + 262, RegionName.otr),
    LocationName.otr_min4: LocationData(base_location_id + 263, RegionName.otrf),
    LocationName.otr_min5: LocationData(base_location_id + 264, RegionName.otrf),
    LocationName.otr_min6: LocationData(base_location_id + 265, RegionName.otr),
    LocationName.otr_min7: LocationData(base_location_id + 266, RegionName.otrf),
    LocationName.otr_min8: LocationData(base_location_id + 267, RegionName.otrf),
    LocationName.otr_min9: LocationData(base_location_id + 268, RegionName.otrf),
    LocationName.otr_min10: LocationData(base_location_id + 269, RegionName.otr),
    # Green Fingers
    LocationName.gf_min1: LocationData(base_location_id + 270, RegionName.gf),
    LocationName.gf_min2: LocationData(base_location_id + 271, RegionName.gf),
    LocationName.gf_min3: LocationData(base_location_id + 272, RegionName.gf),
    LocationName.gf_min4: LocationData(base_location_id + 273, RegionName.gff),
    LocationName.gf_min5: LocationData(base_location_id + 274, RegionName.gff),
    LocationName.gf_min6: LocationData(base_location_id + 275, RegionName.gff),
    LocationName.gf_min7: LocationData(base_location_id + 276, RegionName.gff),
    LocationName.gf_min8: LocationData(base_location_id + 277, RegionName.gff),
    LocationName.gf_min9: LocationData(base_location_id + 278, RegionName.gff),
    LocationName.gf_min10: LocationData(base_location_id + 279, RegionName.gff),
    # An Enterprising Theft
    LocationName.aet_min1: LocationData(base_location_id + 280, RegionName.aet),
    LocationName.aet_min2: LocationData(base_location_id + 281, RegionName.aet),
    LocationName.aet_min3: LocationData(base_location_id + 282, RegionName.aet),
    LocationName.aet_min4: LocationData(base_location_id + 283, RegionName.aet),
    LocationName.aet_min5: LocationData(base_location_id + 284, RegionName.aet),
    LocationName.aet_min6: LocationData(base_location_id + 285, RegionName.aet),
    LocationName.aet_min7: LocationData(base_location_id + 286, RegionName.aet),
    LocationName.aet_min8: LocationData(base_location_id + 287, RegionName.aet),
    LocationName.aet_min9: LocationData(base_location_id + 288, RegionName.aet),
    LocationName.aet_min10: LocationData(base_location_id + 289, RegionName.aet),
    # Breaking Blocks
    LocationName.bb_min1: LocationData(base_location_id + 290, RegionName.bb),
    LocationName.bb_min2: LocationData(base_location_id + 291, RegionName.bbf),
    LocationName.bb_min3: LocationData(base_location_id + 292, RegionName.bbf),
    LocationName.bb_min4: LocationData(base_location_id + 293, RegionName.bbf),
    LocationName.bb_min5: LocationData(base_location_id + 294, RegionName.bbf),
    LocationName.bb_min6: LocationData(base_location_id + 295, RegionName.bbf),
    LocationName.bb_min7: LocationData(base_location_id + 296, RegionName.bbf),
    LocationName.bb_min8: LocationData(base_location_id + 297, RegionName.bbf),
    LocationName.bb_min9: LocationData(base_location_id + 298, RegionName.bbf),
    LocationName.bb_min10: LocationData(base_location_id + 299, RegionName.bbf),
    # Rockin' the Docks
    LocationName.rtd_min1: LocationData(base_location_id + 300, RegionName.rtdf),
    LocationName.rtd_min2: LocationData(base_location_id + 301, RegionName.rtdf),
    LocationName.rtd_min3: LocationData(base_location_id + 302, RegionName.rtd),
    LocationName.rtd_min4: LocationData(base_location_id + 303, RegionName.rtd),
    LocationName.rtd_min5: LocationData(base_location_id + 304, RegionName.rtdf),
    LocationName.rtd_min6: LocationData(base_location_id + 305, RegionName.rtd),
    LocationName.rtd_min7: LocationData(base_location_id + 306, RegionName.rtdf),
    LocationName.rtd_min8: LocationData(base_location_id + 307, RegionName.rtd),
    LocationName.rtd_min9: LocationData(base_location_id + 308, RegionName.rtdf),
    LocationName.rtd_min10: LocationData(base_location_id + 309, RegionName.rtd),
    # Stealing the Show
    LocationName.sts_min1: LocationData(base_location_id + 310, RegionName.sts),
    LocationName.sts_min2: LocationData(base_location_id + 311, RegionName.sts),
    LocationName.sts_min3: LocationData(base_location_id + 312, RegionName.sts),
    LocationName.sts_min4: LocationData(base_location_id + 313, RegionName.sts),
    LocationName.sts_min5: LocationData(base_location_id + 314, RegionName.sts),
    LocationName.sts_min6: LocationData(base_location_id + 315, RegionName.stsf),
    LocationName.sts_min7: LocationData(base_location_id + 316, RegionName.stsf),
    LocationName.sts_min8: LocationData(base_location_id + 317, RegionName.sts),
    LocationName.sts_min9: LocationData(base_location_id + 318, RegionName.stsf),
    LocationName.sts_min10: LocationData(base_location_id + 319, RegionName.stsf),
    # Harbouring a Grudge
    LocationName.hag_min1: LocationData(base_location_id + 320, RegionName.hag),
    LocationName.hag_min2: LocationData(base_location_id + 321, RegionName.hag),
    LocationName.hag_min3: LocationData(base_location_id + 322, RegionName.hagf),
    LocationName.hag_min4: LocationData(base_location_id + 323, RegionName.hag),
    LocationName.hag_min5: LocationData(base_location_id + 324, RegionName.hag),
    LocationName.hag_min6: LocationData(base_location_id + 325, RegionName.hag),
    LocationName.hag_min7: LocationData(base_location_id + 326, RegionName.hag),
    LocationName.hag_min8: LocationData(base_location_id + 327, RegionName.hagf),
    LocationName.hag_min9: LocationData(base_location_id + 328, RegionName.hag),
    LocationName.hag_min10: LocationData(base_location_id + 329, RegionName.hagf),
    # A Daring Rescue
    LocationName.adr_min1: LocationData(base_location_id + 330, RegionName.adr),
    LocationName.adr_min2: LocationData(base_location_id + 331, RegionName.adrf),
    LocationName.adr_min3: LocationData(base_location_id + 332, RegionName.adrf),
    LocationName.adr_min4: LocationData(base_location_id + 333, RegionName.adr),
    LocationName.adr_min5: LocationData(base_location_id + 334, RegionName.adrf),
    LocationName.adr_min6: LocationData(base_location_id + 335, RegionName.adrf),
    LocationName.adr_min7: LocationData(base_location_id + 336, RegionName.adrf),
    LocationName.adr_min8: LocationData(base_location_id + 337, RegionName.adr),
    LocationName.adr_min9: LocationData(base_location_id + 338, RegionName.adrf),
    LocationName.adr_min10: LocationData(base_location_id + 339, RegionName.adr),
    # Arctic World
    LocationName.aw_min1: LocationData(base_location_id + 340, RegionName.aw),
    LocationName.aw_min2: LocationData(base_location_id + 341, RegionName.aw),
    LocationName.aw_min3: LocationData(base_location_id + 342, RegionName.aw),
    LocationName.aw_min4: LocationData(base_location_id + 343, RegionName.aw),
    LocationName.aw_min5: LocationData(base_location_id + 344, RegionName.awf),
    LocationName.aw_min6: LocationData(base_location_id + 345, RegionName.awf),
    LocationName.aw_min7: LocationData(base_location_id + 346, RegionName.aw),
    LocationName.aw_min8: LocationData(base_location_id + 347, RegionName.aw),
    LocationName.aw_min9: LocationData(base_location_id + 348, RegionName.awf),
    LocationName.aw_min10: LocationData(base_location_id + 349, RegionName.awf),
    # A Surprise for the Commissioner
    LocationName.asftc_min1: LocationData(base_location_id + 350, RegionName.asftcf),
    LocationName.asftc_min2: LocationData(base_location_id + 351, RegionName.asftcf),
    LocationName.asftc_min3: LocationData(base_location_id + 352, RegionName.asftcf),
    LocationName.asftc_min4: LocationData(base_location_id + 353, RegionName.asftcf),
    LocationName.asftc_min5: LocationData(base_location_id + 354, RegionName.asftcf),
    LocationName.asftc_min6: LocationData(base_location_id + 355, RegionName.asftc),
    LocationName.asftc_min7: LocationData(base_location_id + 356, RegionName.asftcf),
    LocationName.asftc_min8: LocationData(base_location_id + 357, RegionName.asftcf),
    LocationName.asftc_min9: LocationData(base_location_id + 358, RegionName.asftcf),
    LocationName.asftc_min10: LocationData(base_location_id + 359, RegionName.asftc),
    # Biplane Blast
    LocationName.bbpl_min1: LocationData(base_location_id + 360, RegionName.bbplf),
    LocationName.bbpl_min2: LocationData(base_location_id + 361, RegionName.bbpl),
    LocationName.bbpl_min3: LocationData(base_location_id + 362, RegionName.bbpl),
    LocationName.bbpl_min4: LocationData(base_location_id + 363, RegionName.bbpl),
    LocationName.bbpl_min5: LocationData(base_location_id + 364, RegionName.bbpl),
    LocationName.bbpl_min6: LocationData(base_location_id + 365, RegionName.bbpl),
    LocationName.bbpl_min7: LocationData(base_location_id + 366, RegionName.bbpl),
    LocationName.bbpl_min8: LocationData(base_location_id + 367, RegionName.bbplf),
    LocationName.bbpl_min9: LocationData(base_location_id + 368, RegionName.bbplf),
    LocationName.bbpl_min10: LocationData(base_location_id + 369, RegionName.bbplf),
    # The Joker's Masterpiece
    LocationName.tjm_min1: LocationData(base_location_id + 370, RegionName.tjm),
    LocationName.tjm_min2: LocationData(base_location_id + 371, RegionName.tjm),
    LocationName.tjm_min3: LocationData(base_location_id + 372, RegionName.tjmf),
    LocationName.tjm_min4: LocationData(base_location_id + 373, RegionName.tjm),
    LocationName.tjm_min5: LocationData(base_location_id + 374, RegionName.tjmf),
    LocationName.tjm_min6: LocationData(base_location_id + 375, RegionName.tjmf),
    LocationName.tjm_min7: LocationData(base_location_id + 376, RegionName.tjmf),
    LocationName.tjm_min8: LocationData(base_location_id + 377, RegionName.tjmf),
    LocationName.tjm_min9: LocationData(base_location_id + 378, RegionName.tjmf),
    LocationName.tjm_min10: LocationData(base_location_id + 379, RegionName.tjm),
    # The Lure of the Night
    LocationName.tlotn_min1: LocationData(base_location_id + 380, RegionName.tlotn),
    LocationName.tlotn_min2: LocationData(base_location_id + 381, RegionName.tlotnf),
    LocationName.tlotn_min3: LocationData(base_location_id + 382, RegionName.tlotnf),
    LocationName.tlotn_min4: LocationData(base_location_id + 383, RegionName.tlotnf),
    LocationName.tlotn_min5: LocationData(base_location_id + 384, RegionName.tlotnf),
    LocationName.tlotn_min6: LocationData(base_location_id + 385, RegionName.tlotn),
    LocationName.tlotn_min7: LocationData(base_location_id + 386, RegionName.tlotn),
    LocationName.tlotn_min8: LocationData(base_location_id + 387, RegionName.tlotn),
    LocationName.tlotn_min9: LocationData(base_location_id + 388, RegionName.tlotnf),
    LocationName.tlotn_min10: LocationData(base_location_id + 389, RegionName.tlotnf),
    # Dying of Laughter
    LocationName.dol_min1: LocationData(base_location_id + 390, RegionName.dol),
    LocationName.dol_min2: LocationData(base_location_id + 391, RegionName.dol),
    LocationName.dol_min3: LocationData(base_location_id + 392, RegionName.dol),
    LocationName.dol_min4: LocationData(base_location_id + 393, RegionName.dolf),
    LocationName.dol_min5: LocationData(base_location_id + 394, RegionName.dolf),
    LocationName.dol_min6: LocationData(base_location_id + 395, RegionName.dolf),
    LocationName.dol_min7: LocationData(base_location_id + 396, RegionName.dolf),
    LocationName.dol_min8: LocationData(base_location_id + 397, RegionName.dolf),
    LocationName.dol_min9: LocationData(base_location_id + 398, RegionName.dol),
    LocationName.dol_min10: LocationData(base_location_id + 399, RegionName.dolf),
}

hostage_location_table: Dict[str, LocationData] = {
    LocationName.ycbob_host: LocationData(base_location_id + 400, RegionName.ycbob),
    LocationName.air_host: LocationData(base_location_id + 401, RegionName.air),
    LocationName.apa_host: LocationData(base_location_id + 402, RegionName.apa),
    LocationName.tfo_host: LocationData(base_location_id + 403, RegionName.tfo),
    LocationName.tsga_host: LocationData(base_location_id + 404, RegionName.tsgaf),
    LocationName.utc_host: LocationData(base_location_id + 405, RegionName.utc),
    LocationName.zc_host: LocationData(base_location_id + 406, RegionName.zcf),
    LocationName.pl_host: LocationData(base_location_id + 407, RegionName.plf),
    LocationName.jht_host: LocationData(base_location_id + 408, RegionName.jht),
    LocationName.lfabt_host: LocationData(base_location_id + 409, RegionName.lfabtf),
    LocationName.itdn_host: LocationData(base_location_id + 410, RegionName.itdnf),
    LocationName.tttot_host: LocationData(base_location_id + 411, RegionName.tttot),
    LocationName.trmaw_host: LocationData(base_location_id + 412, RegionName.trmawf),
    LocationName.otr_host: LocationData(base_location_id + 413, RegionName.otrf),
    LocationName.gf_host: LocationData(base_location_id + 414, RegionName.gf),
    LocationName.aet_host: LocationData(base_location_id + 415, RegionName.aet),
    LocationName.bb_host: LocationData(base_location_id + 416, RegionName.bbf),
    LocationName.rtd_host: LocationData(base_location_id + 417, RegionName.rtdf),
    LocationName.sts_host: LocationData(base_location_id + 418, RegionName.sts),
    LocationName.adr_host: LocationData(base_location_id + 419, RegionName.adrf),
    LocationName.aw_host: LocationData(base_location_id + 420, RegionName.aw),
    LocationName.asftc_host: LocationData(base_location_id + 421, RegionName.asftcf),
    LocationName.tjm_host: LocationData(base_location_id + 422, RegionName.tjm),
    LocationName.tlotn_host: LocationData(base_location_id + 423, RegionName.tlotnf),
    LocationName.dol_host: LocationData(base_location_id + 424, RegionName.dolf),
}

level_beaten_location_table: Dict[str, LocationData] = {
    LocationName.ycbob_beat: LocationData(base_location_id + 425, RegionName.ycbob),
    LocationName.air_beat: LocationData(base_location_id + 426, RegionName.air),
    LocationName.tfc_beat: LocationData(base_location_id + 427, RegionName.tfc),
    LocationName.apa_beat: LocationData(base_location_id + 428, RegionName.apa),
    LocationName.tfo_beat: LocationData(base_location_id + 429, RegionName.tfo),
    LocationName.tsga_beat: LocationData(base_location_id + 430, RegionName.tsga),
    LocationName.bbb_beat: LocationData(base_location_id + 431, RegionName.bbb),
    LocationName.utc_beat: LocationData(base_location_id + 432, RegionName.utc),
    LocationName.zc_beat: LocationData(base_location_id + 433, RegionName.zc),
    LocationName.pl_beat: LocationData(base_location_id + 434, RegionName.pl),
    LocationName.jht_beat: LocationData(base_location_id + 435, RegionName.jht),
    LocationName.lfabt_beat: LocationData(base_location_id + 436, RegionName.lfabt),
    LocationName.fotb_beat: LocationData(base_location_id + 437, RegionName.fotb),
    LocationName.itdn_beat: LocationData(base_location_id + 438, RegionName.itdn),
    LocationName.tttot_beat: LocationData(base_location_id + 439, RegionName.tttot),
    LocationName.trmaw_beat: LocationData(base_location_id + 440, RegionName.trmaw),
    LocationName.otr_beat: LocationData(base_location_id + 441, RegionName.otr),
    LocationName.gf_beat: LocationData(base_location_id + 442, RegionName.gf),
    LocationName.aet_beat: LocationData(base_location_id + 443, RegionName.aet),
    LocationName.bb_beat: LocationData(base_location_id + 444, RegionName.bb),
    LocationName.rtd_beat: LocationData(base_location_id + 445, RegionName.rtd),
    LocationName.sts_beat: LocationData(base_location_id + 446, RegionName.sts),
    LocationName.hag_beat: LocationData(base_location_id + 447, RegionName.hag),
    LocationName.adr_beat: LocationData(base_location_id + 448, RegionName.adr),
    LocationName.aw_beat: LocationData(base_location_id + 449, RegionName.aw),
    LocationName.asftc_beat: LocationData(base_location_id + 450, RegionName.asftc),
    LocationName.bbpl_beat: LocationData(base_location_id + 451, RegionName.bbpl),
    LocationName.tjm_beat: LocationData(base_location_id + 452, RegionName.tjm),
    LocationName.tlotn_beat: LocationData(base_location_id + 453, RegionName.tlotn),
    LocationName.dol_beat: LocationData(base_location_id + 454, RegionName.dol),
}

true_status_location_table: Dict[str, LocationData] = {
    LocationName.ycbob_ts: LocationData(base_location_id + 455, RegionName.ycbob),
    LocationName.air_ts: LocationData(base_location_id + 456, RegionName.air),
    LocationName.tfc_ts: LocationData(base_location_id + 457, RegionName.tfc),
    LocationName.apa_ts: LocationData(base_location_id + 458, RegionName.apa),
    LocationName.tfo_ts: LocationData(base_location_id + 459, RegionName.tfo),
    LocationName.tsga_ts: LocationData(base_location_id + 460, RegionName.tsga),
    LocationName.bbb_ts: LocationData(base_location_id + 461, RegionName.bbb),
    LocationName.utc_ts: LocationData(base_location_id + 462, RegionName.utc),
    LocationName.zc_ts: LocationData(base_location_id + 463, RegionName.zc),
    LocationName.pl_ts: LocationData(base_location_id + 464, RegionName.pl),
    LocationName.jht_ts: LocationData(base_location_id + 465, RegionName.jht),
    LocationName.lfabt_ts: LocationData(base_location_id + 466, RegionName.lfabt),
    LocationName.fotb_ts: LocationData(base_location_id + 467, RegionName.fotb),
    LocationName.itdn_ts: LocationData(base_location_id + 468, RegionName.itdnf),
    LocationName.tttot_ts: LocationData(base_location_id + 469, RegionName.tttotf),
    LocationName.trmaw_ts: LocationData(base_location_id + 470, RegionName.trmaw),
    LocationName.otr_ts: LocationData(base_location_id + 471, RegionName.otr),
    LocationName.gf_ts: LocationData(base_location_id + 472, RegionName.gf),
    LocationName.aet_ts: LocationData(base_location_id + 473, RegionName.aet),
    LocationName.bb_ts: LocationData(base_location_id + 474, RegionName.bb),
    LocationName.rtd_ts: LocationData(base_location_id + 475, RegionName.rtd),
    LocationName.sts_ts: LocationData(base_location_id + 476, RegionName.sts),
    LocationName.hag_ts: LocationData(base_location_id + 477, RegionName.hag),
    LocationName.adr_ts: LocationData(base_location_id + 478, RegionName.adr),
    LocationName.aw_ts: LocationData(base_location_id + 479, RegionName.aw),
    LocationName.asftc_ts: LocationData(base_location_id + 480, RegionName.asftc),
    LocationName.bbpl_ts: LocationData(base_location_id + 481, RegionName.bbpl),
    LocationName.tjm_ts: LocationData(base_location_id + 482, RegionName.tjm),
    LocationName.tlotn_ts: LocationData(base_location_id + 483, RegionName.tlotn),
    LocationName.dol_ts: LocationData(base_location_id + 484, RegionName.dol),
}

red_brick_location_table: Dict[str, LocationData] = {
    LocationName.ycbob_rb: LocationData(base_location_id + 485, RegionName.ycbob),
    LocationName.air_rb: LocationData(base_location_id + 486, RegionName.airf),
    LocationName.tfc_rb: LocationData(base_location_id + 487, RegionName.tfc),
    LocationName.apa_rb: LocationData(base_location_id + 488, RegionName.apaf),
    LocationName.tfo_rb: LocationData(base_location_id + 489, RegionName.tfof),
    LocationName.tsga_rb: LocationData(base_location_id + 490, RegionName.tsgaf),
    LocationName.bbb_rb: LocationData(base_location_id + 491, RegionName.bbbf),
    LocationName.utc_rb: LocationData(base_location_id + 492, RegionName.utc),
    LocationName.zc_rb: LocationData(base_location_id + 493, RegionName.zcf),
    LocationName.pl_rb: LocationData(base_location_id + 494, RegionName.plf),
    LocationName.jht_rb: LocationData(base_location_id + 495, RegionName.jht),
    LocationName.lfabt_rb: LocationData(base_location_id + 496, RegionName.lfabt),
    LocationName.fotb_rb: LocationData(base_location_id + 497, RegionName.fotb),
    LocationName.itdn_rb: LocationData(base_location_id + 498, RegionName.itdnf),
    LocationName.tttot_rb: LocationData(base_location_id + 499, RegionName.tttot),
    LocationName.trmaw_rb: LocationData(base_location_id + 500, RegionName.trmawf),
    LocationName.otr_rb: LocationData(base_location_id + 501, RegionName.otrf),
    LocationName.gf_rb: LocationData(base_location_id + 502, RegionName.gf),
    LocationName.aet_rb: LocationData(base_location_id + 503, RegionName.aet),
    LocationName.bb_rb: LocationData(base_location_id + 504, RegionName.bbf),
    LocationName.rtd_rb: LocationData(base_location_id + 505, RegionName.rtdf),
    LocationName.sts_rb: LocationData(base_location_id + 506, RegionName.stsf),
    LocationName.hag_rb: LocationData(base_location_id + 507, RegionName.hagf),
    LocationName.adr_rb: LocationData(base_location_id + 508, RegionName.adrf),
    LocationName.aw_rb: LocationData(base_location_id + 509, RegionName.aw),
    LocationName.asftc_rb: LocationData(base_location_id + 510, RegionName.asftcf),
    LocationName.bbpl_rb: LocationData(base_location_id + 511, RegionName.bbpl),
    LocationName.tjm_rb: LocationData(base_location_id + 512, RegionName.tjm),
    LocationName.tlotn_rb: LocationData(base_location_id + 513, RegionName.tlotnf),
    LocationName.dol_rb: LocationData(base_location_id + 514, RegionName.dol),
}

red_brick_purchase_table: Dict[str, LocationData] = {
    LocationName.silhouettes: LocationData(base_location_id + 515, RegionName.sh, 10000),
    LocationName.beepbeep: LocationData(base_location_id + 516, RegionName.sh, 20000),
    LocationName.icerink: LocationData(base_location_id + 517, RegionName.sh, 30000),
    LocationName.disguise: LocationData(base_location_id + 518, RegionName.sh, 40000),
    LocationName.extratoggle: LocationData(base_location_id + 519, RegionName.sh, 50000),
    LocationName.scorex2: LocationData(base_location_id + 520, RegionName.sh, 1000000),
    LocationName.scorex4: LocationData(base_location_id + 521, RegionName.sh, 2000000),
    LocationName.scorex6: LocationData(base_location_id + 522, RegionName.sh, 3000000),
    LocationName.scorex8: LocationData(base_location_id + 523, RegionName.sh, 4000000),
    LocationName.scorex10: LocationData(base_location_id + 524, RegionName.sh, 5000000),
    LocationName.studmagnet: LocationData(base_location_id + 525, RegionName.sh, 100000),
    LocationName.charstuds: LocationData(base_location_id + 526, RegionName.sh, 200000),
    LocationName.minikitdetect: LocationData(base_location_id + 527, RegionName.sh, 300000),
    LocationName.pwrbrickdetect: LocationData(base_location_id + 528, RegionName.sh, 400000),
    LocationName.alwaysscore: LocationData(base_location_id + 529, RegionName.sh, 500000),
    LocationName.fastbuild: LocationData(base_location_id + 530, RegionName.sh, 100000),
    LocationName.immunefreeze: LocationData(base_location_id + 531, RegionName.sh, 200000),
    LocationName.regenhearts: LocationData(base_location_id + 532, RegionName.sh, 300000),
    LocationName.extrahearts: LocationData(base_location_id + 533, RegionName.sh, 400000),
    LocationName.invincibility: LocationData(base_location_id + 534, RegionName.sh, 500000),
    LocationName.fastgrapple: LocationData(base_location_id + 535, RegionName.sh, 10000),
    LocationName.fastbatarang: LocationData(base_location_id + 536, RegionName.sh, 20000),
    LocationName.moretargets: LocationData(base_location_id + 537, RegionName.sh, 30000),
    LocationName.flamingbata: LocationData(base_location_id + 538, RegionName.sh, 40000),
    LocationName.slam: LocationData(base_location_id + 539, RegionName.sh, 50000),
    LocationName.moredet: LocationData(base_location_id + 540, RegionName.sh, 10000),
    LocationName.armorplating: LocationData(base_location_id + 541, RegionName.sh, 20000),
    LocationName.sonicpain: LocationData(base_location_id + 542, RegionName.sh, 30000),
    LocationName.areaeffect: LocationData(base_location_id + 543, RegionName.sh, 40000),
    LocationName.bats: LocationData(base_location_id + 544, RegionName.sh, 50000),
    LocationName.freezebatarang: LocationData(base_location_id + 545, RegionName.sh, 10000),
    LocationName.decoy: LocationData(base_location_id + 546, RegionName.sh, 20000),
    LocationName.fastwalk: LocationData(base_location_id + 547, RegionName.sh, 30000),
    LocationName.fasterpieces: LocationData(base_location_id + 548, RegionName.sh, 40000),
    LocationName.piecedetect: LocationData(base_location_id + 549, RegionName.sh, 50000),
}

character_token_table: Dict[str, LocationData] = {
    # LocationName.batman_collected: LocationData(base_location_id + 550, RegionName.bc),
    # LocationName.robin_collected: LocationData(base_location_id + 551, RegionName.bc),
    LocationName.brucewayne_collected: LocationData(base_location_id + 552, RegionName.bc),
    LocationName.alfred_collected: LocationData(base_location_id + 553, RegionName.bc),
    LocationName.batgirl_collected: LocationData(base_location_id + 554, RegionName.bc),
    LocationName.nightwing_collected: LocationData(base_location_id + 555, RegionName.bc),
    LocationName.commissionergordon_collected: LocationData(base_location_id + 556, RegionName.asftc),
    LocationName.policeofficer_collected: LocationData(base_location_id + 557, RegionName.bc),
    LocationName.fishmonger_collected: LocationData(base_location_id + 558, RegionName.tsga),
    LocationName.militarypoliceman_collected: LocationData(base_location_id + 559, RegionName.bc),
    LocationName.securityguard_collected: LocationData(base_location_id + 560, RegionName.bc),
    LocationName.swat_collected: LocationData(base_location_id + 561, RegionName.bb),
    LocationName.scientist_collected: LocationData(base_location_id + 562, RegionName.aet),
    LocationName.sailor_collected: LocationData(base_location_id + 563, RegionName.rtd),
    LocationName.policemarksman_collected: LocationData(base_location_id + 564, RegionName.dol),
    # LocationName.clayface_collected: LocationData(base_location_id + 565, RegionName.trmaw),
    # LocationName.mrfreeze_collected: LocationData(base_location_id + 566, RegionName.otr),
    # LocationName.poisonivy_collected: LocationData(base_location_id + 567, RegionName.apa),
    # LocationName.twoface_collected: LocationData(base_location_id + 568, RegionName.bb),
    # LocationName.riddler_collected: LocationData(base_location_id + 569, RegionName.ycbob),
    # LocationName.bane_collected: LocationData(base_location_id + 570, RegionName.rtd),
    # LocationName.catwoman_collected: LocationData(base_location_id + 571, RegionName.sts),
    LocationName.catwomanclassic_collected: LocationData(base_location_id + 572, RegionName.sts),
    # LocationName.killercroc_collected: LocationData(base_location_id + 573, RegionName.adr),
    LocationName.manbat_collected: LocationData(base_location_id + 574, RegionName.pl),
    # LocationName.penguin_collected: LocationData(base_location_id + 575, RegionName.tsga),
    # LocationName.harleyquinn_collected: LocationData(base_location_id + 576, RegionName.jht),
    # LocationName.scarecrow_collected: LocationData(base_location_id + 577, RegionName.tlotn),
    # LocationName.killermoth_collected: LocationData(base_location_id + 578, RegionName.tlotn),
    LocationName.madhatter_collected: LocationData(base_location_id + 579, RegionName.jht),
    # LocationName.joker_collected: LocationData(base_location_id + 580, RegionName.jht),
    LocationName.jokertropical_collected: LocationData(base_location_id + 581, RegionName.dol),
    LocationName.poisonivygoon_collected: LocationData(base_location_id + 582, RegionName.apa),
    LocationName.zoosweeper_collected: LocationData(base_location_id + 583, RegionName.zc),
    LocationName.freezegirl_collected: LocationData(base_location_id + 584, RegionName.air),
    LocationName.yeti_collected: LocationData(base_location_id + 585, RegionName.pl),
    LocationName.riddlergoon_collected: LocationData(base_location_id + 586, RegionName.ycbob),
    LocationName.riddlerhenchman_collected: LocationData(base_location_id + 587, RegionName.ycbob),
    LocationName.penguingoon_collected: LocationData(base_location_id + 588, RegionName.tsga),
    LocationName.penguinhenchman_collected: LocationData(base_location_id + 589, RegionName.tsga),
    LocationName.penguinminion_collected: LocationData(base_location_id + 590, RegionName.pl),
    LocationName.jokergoon_collected: LocationData(base_location_id + 591, RegionName.jht),
    LocationName.jokerhenchman_collected: LocationData(base_location_id + 592, RegionName.jht),
    LocationName.clowngoon_collected: LocationData(base_location_id + 593, RegionName.lfabt),
    # LocationName.hero1_collected: LocationData(base_location_id + 596, RegionName.tjm),
    # LocationName.hero2_collected: LocationData(base_location_id + 597, RegionName.tjm),
    # LocationName.batmobile_collected: LocationData(base_location_id + 598, RegionName.tfc),
    # LocationName.batcycle_collected: LocationData(base_location_id + 599, RegionName.tfc),
    LocationName.policecar_collected: LocationData(base_location_id + 600, RegionName.tfc),
    LocationName.policebike_collected: LocationData(base_location_id + 601, RegionName.tfc),
    LocationName.policevan_collected: LocationData(base_location_id + 602, RegionName.tfc),
    LocationName.battank_collected: LocationData(base_location_id + 603, RegionName.bc),
    LocationName.catmotorcycle_collected: LocationData(base_location_id + 604, RegionName.sts),
    LocationName.armouredtruck_collected: LocationData(base_location_id + 605, RegionName.aet),
    LocationName.freezekart_collected: LocationData(base_location_id + 606, RegionName.otr),
    LocationName.hammertruck_collected: LocationData(base_location_id + 607, RegionName.asftc),
    LocationName.jokervan_collected: LocationData(base_location_id + 608, RegionName.tfc),
    LocationName.garbagetruck_collected: LocationData(base_location_id + 609, RegionName.tlotn),
    # LocationName.batboat_collected: LocationData(base_location_id + 610, RegionName.bbb),
    # LocationName.robinswatercraft_collected: LocationData(base_location_id + 611, RegionName.bbb),
    LocationName.robinssubmarine_collected: LocationData(base_location_id + 612, RegionName.bbb),
    LocationName.policewatercraft_collected: LocationData(base_location_id + 613, RegionName.hag),
    LocationName.policeboat_collected: LocationData(base_location_id + 614, RegionName.hag),
    # LocationName.penguinsubmarine_collected: LocationData(base_location_id + 615, RegionName.hag),
    # LocationName.swamprider_collected: LocationData(base_location_id + 616, RegionName.hag),
    LocationName.penguingoonsub_collected: LocationData(base_location_id + 617, RegionName.bbb),
    LocationName.iceberg_collected: LocationData(base_location_id + 618, RegionName.otr),
    LocationName.steamboat_collected: LocationData(base_location_id + 619, RegionName.jht),
    # LocationName.batwing_collected: LocationData(base_location_id + 620, RegionName.fotb),
    # LocationName.batcopter_collected: LocationData(base_location_id + 621, RegionName.fotb),
    LocationName.harbourhelicopter_collected: LocationData(base_location_id + 622, RegionName.bbb),
    LocationName.policehelicopter_collected: LocationData(base_location_id + 623, RegionName.bbpl),
    LocationName.privatejet_collected: LocationData(base_location_id + 624, RegionName.fotb),
    # LocationName.jokerhelicopter_collected: LocationData(base_location_id + 625, RegionName.bbpl),
    # LocationName.scarecrowbiplane_collected: LocationData(base_location_id + 626, RegionName.bbpl),
    LocationName.goonhelicopter_collected: LocationData(base_location_id + 627, RegionName.bbpl),
    LocationName.riddlerjet_collected: LocationData(base_location_id + 628, RegionName.bb),
    LocationName.glider_collected: LocationData(base_location_id + 629, RegionName.jht),
}

hard_character_token_table: Dict[str, LocationData] = {
    LocationName.hush_collected: LocationData(base_location_id + 594, RegionName.bc),
    LocationName.rasalghul_collected: LocationData(base_location_id + 595, RegionName.bc),
}

event_location_table = {
    LocationName.ycbob_token: LocationData(0, RegionName.ycbob),
    LocationName.air_token: LocationData(0, RegionName.air),
    LocationName.tfc_token: LocationData(0, RegionName.tfc),
    LocationName.apa_token: LocationData(0, RegionName.apa),
    LocationName.tfo_token: LocationData(0, RegionName.tfo),
    LocationName.tsga_token: LocationData(0, RegionName.tsga),
    LocationName.bbb_token: LocationData(0, RegionName.bbb),
    LocationName.utc_token: LocationData(0, RegionName.utc),
    LocationName.zc_token: LocationData(0, RegionName.zc),
    LocationName.pl_token: LocationData(0, RegionName.pl),
    LocationName.jht_token: LocationData(0, RegionName.jht),
    LocationName.lfabt_token: LocationData(0, RegionName.lfabt),
    LocationName.fotb_token: LocationData(0, RegionName.fotb),
    LocationName.itdn_token: LocationData(0, RegionName.itdn),
    LocationName.tttot_token: LocationData(0, RegionName.tttot),
    LocationName.trmaw_token: LocationData(0, RegionName.trmaw),
    LocationName.otr_token: LocationData(0, RegionName.otr),
    LocationName.gf_token: LocationData(0, RegionName.gf),
    LocationName.aet_token: LocationData(0, RegionName.aet),
    LocationName.bb_token: LocationData(0, RegionName.bb),
    LocationName.rtd_token: LocationData(0, RegionName.rtd),
    LocationName.sts_token: LocationData(0, RegionName.sts),
    LocationName.hag_token: LocationData(0, RegionName.hag),
    LocationName.adr_token: LocationData(0, RegionName.adr),
    LocationName.aw_token: LocationData(0, RegionName.aw),
    LocationName.asftc_token: LocationData(0, RegionName.asftc),
    LocationName.bbpl_token: LocationData(0, RegionName.bbpl),
    LocationName.tjm_token: LocationData(0, RegionName.tjm),
    LocationName.tlotn_token: LocationData(0, RegionName.tlotn),
    LocationName.dol_token: LocationData(0, RegionName.dol),
}

all_location_table = {
    **character_location_table,
    **hard_character_location_table,
    # **suit_location_table,
    **minikit_location_table,
    **hostage_location_table,
    **level_beaten_location_table,
    **true_status_location_table,
    **red_brick_location_table,
    **red_brick_purchase_table,
    **character_token_table,
    **hard_character_token_table,
}

purchase_location_table = {
    **character_location_table,
    **red_brick_purchase_table,
    **hard_character_location_table,
}


def setup_locations(options: LB1Options):
    temp_location_table = {}
    if options.minikit_sanity == 1:
        temp_location_table.update({**minikit_location_table})
    if options.true_status_sanity == 1:
        temp_location_table.update({**true_status_location_table})
    temp_location_table.update({**character_location_table})
    if options.shuffle_hush_and_ras == 1:
        temp_location_table.update({**hard_character_location_table})
    # temp_location_table.update({**suit_location_table})
    temp_location_table.update({**hostage_location_table})
    temp_location_table.update({**level_beaten_location_table})
    temp_location_table.update({**red_brick_location_table})
    temp_location_table.update({**red_brick_purchase_table})
    if options.decouple_character_tokens == 1:
        temp_location_table.update({**character_token_table})
    if options.decouple_hush_and_ras_token == 1:
        temp_location_table.update({**hard_character_token_table})
    return temp_location_table
