from typing import Dict, NamedTuple

from BaseClasses import Location
from .Options import LB1Options
from .Names import LocationName


class LB1Location(Location):
    game: str = "Lego Batman: The Videogame"


class LocationData(NamedTuple):
    id: int = 0
    region: str = ""


base_location_id: int = 400000

character_location_table: Dict[str, LocationData] = {
    LocationName.batman_collected: LocationData(base_location_id + 0, "Batcave"),
    LocationName.robin_collected: LocationData(base_location_id + 1, "Batcave"),
    LocationName.brucewayne_collected: LocationData(base_location_id + 2, "The Face-Off"),
    LocationName.alfred_collected: LocationData(base_location_id + 3, "The Face-Off"),
    LocationName.batgirl_collected: LocationData(base_location_id + 4, "The Face-Off"),
    LocationName.nightwing_collected: LocationData(base_location_id + 5, "The Face-Off"),
    LocationName.commissionergordon_collected: LocationData(base_location_id + 6, "A Surprise for the Commissioner"),
    LocationName.policeofficer_collected: LocationData(base_location_id + 7, "The Face-Off"),
    LocationName.fishmonger_collected: LocationData(base_location_id + 8, "There She Goes Again"),
    LocationName.militarypoliceman_collected: LocationData(base_location_id + 9, "The Face-Off"),
    LocationName.securityguard_collected: LocationData(base_location_id + 10, "The Face-Off"),
    LocationName.swat_collected: LocationData(base_location_id + 11, "Breaking Blocks"),
    LocationName.scientist_collected: LocationData(base_location_id + 12, "An Enterprising Theft"),
    LocationName.sailor_collected: LocationData(base_location_id + 13, "Rockin' the Docks"),
    LocationName.policemarksman_collected: LocationData(base_location_id + 14, "Dying of Laughter"),
    LocationName.clayface_collected: LocationData(base_location_id + 15, "The Riddler Makes a Withdrawal"),
    LocationName.mrfreeze_collected: LocationData(base_location_id + 16, "On the Rocks"),
    LocationName.poisonivy_collected: LocationData(base_location_id + 17, "Green Fingers"),
    LocationName.twoface_collected: LocationData(base_location_id + 18, "An Enterprising Theft"),   # check about Breaking Blocks
    LocationName.riddler_collected: LocationData(base_location_id + 19, "Arkham Asylum"),
    LocationName.bane_collected: LocationData(base_location_id + 20, "Rockin' the Docks"),
    LocationName.catwoman_collected: LocationData(base_location_id + 21, "Stealing the Show"),  # Check Arctic World
    LocationName.catwomanclassic_collected: LocationData(base_location_id + 22, "Stealing the Show"),
    LocationName.killercroc_collected: LocationData(base_location_id + 23, "A Daring Rescue"),
    LocationName.manbat_collected: LocationData(base_location_id + 24, "Penguin's Lair"),
    LocationName.penguin_collected: LocationData(base_location_id + 25, "Arkham Asylum"),
    LocationName.harleyquinn_collected: LocationData(base_location_id + 26, "A Surprise for the Commissioner"), # check about Dying of Laughter
    LocationName.scarecrow_collected: LocationData(base_location_id + 27, "The Joker's Masterpiece"),
    LocationName.killermoth_collected: LocationData(base_location_id + 28, "The Lure of the Night"),
    LocationName.madhatter_collected: LocationData(base_location_id + 29, "Joker's Home Turf"),
    LocationName.joker_collected: LocationData(base_location_id + 30, "Arkham Asylum"),
    LocationName.jokertropical_collected: LocationData(base_location_id + 31, "Dying of Laughter"),
    LocationName.poisonivygoon_collected: LocationData(base_location_id + 32, "A Poisonous Appointment"),
    LocationName.zoosweeper_collected: LocationData(base_location_id + 33, "Zoo's Company"),
    LocationName.freezegirl_collected: LocationData(base_location_id + 34, "An Icy Reception"),
    LocationName.yeti_collected: LocationData(base_location_id + 35, "Penguin's Lair"),
    LocationName.riddlergoon_collected: LocationData(base_location_id + 36, "You can Bank on Batman"),
    LocationName.riddlerhenchman_collected: LocationData(base_location_id + 37, "You can Bank on Batman"),
    LocationName.penguingoons_collected: LocationData(base_location_id + 38, "There She Goes Again"),
    LocationName.penguinhenchman_collected: LocationData(base_location_id + 39, "There She Goes Again"),
    LocationName.penguinminion_collected: LocationData(base_location_id + 40, "Penguin's Lair"),
    LocationName.jokergoon_collected: LocationData(base_location_id + 41, "Joker's Home Turf"),
    LocationName.jokerhenchman_collected: LocationData(base_location_id + 42, "Joker's Home Turf"),
    LocationName.clowngoon_collected: LocationData(base_location_id + 43, "Little Fun at the Big Top"),
}

hard_character_location_table: Dict[str, LocationData] = {
    LocationName.hush_collected: LocationData(base_location_id + 44, "Shop"),
    LocationName.rasalghul_collected: LocationData(base_location_id + 45, "Shop"),
    # LocationName.hero1_collected: LocationData(base_location_id + 46, "Batcave"),
    # LocationName.hero2_collected: LocationData(base_location_id + 47, "Batcave"),
}

automobile_location_table: Dict[str, LocationData] = {
    LocationName.batmobile_collected: LocationData(base_location_id + 48, "Two-Face Chase"),
    LocationName.batcycle_collected: LocationData(base_location_id + 49, "Two-Face Chase"),
    LocationName.policecar_collected: LocationData(base_location_id + 50, "Two-Face Chase"),
    LocationName.policebike_collected: LocationData(base_location_id + 51, "Two-Face Chase"),
    LocationName.policevan_collected: LocationData(base_location_id + 52, "Two-Face Chase"),
    LocationName.battank_collected: LocationData(base_location_id + 53, "To the Top of the Tower"),
    LocationName.catmotorcycle_collected: LocationData(base_location_id + 54, "Stealing the Show"),
    LocationName.armouredtruck_collected: LocationData(base_location_id + 55, "An Enterprising Theft"),
    LocationName.freezekart_collected: LocationData(base_location_id + 56, "On the Rocks"),
    LocationName.hammertruck_collected: LocationData(base_location_id + 57, "A Surprise for the Commissioner"),
    LocationName.jokervan_collected: LocationData(base_location_id + 58, "Two-Face Chase"),
    LocationName.garbagetruck_collected: LocationData(base_location_id + 59, "The Lure of the Night"),
}

watercraft_location_table: Dict[str, LocationData] = {
    LocationName.batboat_collected: LocationData(base_location_id + 60, "Batboat Battle"),
    LocationName.robinswatercraft_collected: LocationData(base_location_id + 61, "Batboat Battle"),
    LocationName.robinssubmarine_collected: LocationData(base_location_id + 62, "Batboat Battle"),
    LocationName.policewatercraft_collected: LocationData(base_location_id + 63, "Harbouring a Grudge"),
    LocationName.policeboat_collected: LocationData(base_location_id + 64, "Harbouring a Grudge"),
    LocationName.penguinsubmarine_collected: LocationData(base_location_id + 65, "Harbouring a Grudge"),
    LocationName.swamprider_collected: LocationData(base_location_id + 66, "Harbouring a Grudge"),
    LocationName.penguingoonsub_collected: LocationData(base_location_id + 67, "Batboat Battle"),
    LocationName.iceberg_collected: LocationData(base_location_id + 68, "On the Rocks"),
    LocationName.steamboat_collected: LocationData(base_location_id + 69, "Joker's Home Turf"),
}

aircraft_location_table: Dict[str, LocationData] = {
    LocationName.batwing_collected: LocationData(base_location_id + 70, "Flight of the Bat"),
    LocationName.batcopter_collected: LocationData(base_location_id + 71, "Flight of the Bat"),
    LocationName.harbourhelicopter_collected: LocationData(base_location_id + 72, "Batboat Battle"),
    LocationName.policehelicopter_collected: LocationData(base_location_id + 73, "Biplane Blast"),
    LocationName.privatejet_collected: LocationData(base_location_id + 74, "Flight of the Bat"),
    LocationName.jokerhelicopter_collected: LocationData(base_location_id + 75, "Biplane Blast"),
    LocationName.scarecrowbiplane_collected: LocationData(base_location_id + 76, "Biplane Blast"),
    LocationName.goonhelicopter_collected: LocationData(base_location_id + 77, "Biplane Blast"),
    LocationName.riddlerjet_collected: LocationData(base_location_id + 78, "Breaking Blocks"),
    LocationName.glider_collected: LocationData(base_location_id + 79, "Joker's Home Turf"),
}

# Currently stored in Batcave because it is sounding like they can be unlocked in multiple levels
suit_location_table: Dict[str, LocationData] = {
    # LocationName.batsuit_collected: LocationData(base_location_id + 80, "Batcave"),
    LocationName.heatprotectsuit: LocationData(base_location_id + 81, "Batcave"),
    LocationName.glidesuit: LocationData(base_location_id + 82, "Batcave"),
    LocationName.demosuit: LocationData(base_location_id + 83, "Batcave"),
    LocationName.sonicsuit: LocationData(base_location_id + 84, "Batcave"),
    # LocationName.robinsuit_collected: LocationData(base_location_id + 85, "Batcave"),
    LocationName.watersuit: LocationData(base_location_id + 86, "Batcave"),
    LocationName.techsuit: LocationData(base_location_id + 87, "Batcave"),
    LocationName.magsuit: LocationData(base_location_id + 88, "Batcave"),
    LocationName.attractsuit: LocationData(base_location_id + 89, "Batcave"),
}

minikit_location_table: Dict[str, LocationData] = {
    # You can Bank on Batman
    LocationName.ycbob_min1: LocationData(base_location_id + 100, "You can Bank on Batman"),
    LocationName.ycbob_min2: LocationData(base_location_id + 101, "You can Bank on Batman"),
    LocationName.ycbob_min3: LocationData(base_location_id + 102, "You can Bank on Batman"),
    LocationName.ycbob_min4: LocationData(base_location_id + 103, "You can Bank on Batman"),
    LocationName.ycbob_min5: LocationData(base_location_id + 104, "You can Bank on Batman: Freeplay"),
    LocationName.ycbob_min6: LocationData(base_location_id + 105, "You can Bank on Batman: Freeplay"),
    LocationName.ycbob_min7: LocationData(base_location_id + 106, "You can Bank on Batman: Freeplay"),
    LocationName.ycbob_min8: LocationData(base_location_id + 107, "You can Bank on Batman: Freeplay"),
    LocationName.ycbob_min9: LocationData(base_location_id + 108, "You can Bank on Batman: Freeplay"),
    LocationName.ycbob_min10: LocationData(base_location_id + 109, "You can Bank on Batman: Freeplay"),

    # An Icy Reception
    LocationName.air_min1: LocationData(base_location_id + 110, "An Icy Reception"),
    LocationName.air_min2: LocationData(base_location_id + 111, "An Icy Reception"),
    LocationName.air_min3: LocationData(base_location_id + 112, "An Icy Reception"),
    LocationName.air_min4: LocationData(base_location_id + 113, "An Icy Reception"),
    LocationName.air_min5: LocationData(base_location_id + 114, "An Icy Reception"),
    LocationName.air_min6: LocationData(base_location_id + 115, "An Icy Reception"),
    LocationName.air_min7: LocationData(base_location_id + 116, "An Icy Reception: Freeplay"),
    LocationName.air_min8: LocationData(base_location_id + 117, "An Icy Reception: Freeplay"),
    LocationName.air_min9: LocationData(base_location_id + 118, "An Icy Reception: Freeplay"),
    LocationName.air_min10: LocationData(base_location_id + 119, "An Icy Reception: Freeplay"),
    # Two-Face Chase
    LocationName.tfc_min1: LocationData(base_location_id + 120, "Two-Face Chase"),
    LocationName.tfc_min2: LocationData(base_location_id + 121, "Two-Face Chase"),
    LocationName.tfc_min3: LocationData(base_location_id + 122, "Two-Face Chase"),
    LocationName.tfc_min4: LocationData(base_location_id + 123, "Two-Face Chase"),
    LocationName.tfc_min5: LocationData(base_location_id + 124, "Two-Face Chase"),
    LocationName.tfc_min6: LocationData(base_location_id + 125, "Two-Face Chase"),
    LocationName.tfc_min7: LocationData(base_location_id + 126, "Two-Face Chase: Freeplay"),
    LocationName.tfc_min8: LocationData(base_location_id + 127, "Two-Face Chase: Freeplay"),
    LocationName.tfc_min9: LocationData(base_location_id + 128, "Two-Face Chase"),
    LocationName.tfc_min10: LocationData(base_location_id + 129, "Two-Face Chase: Freeplay"),
    # A Poisonous Appointment
    LocationName.apa_min1: LocationData(base_location_id + 130, "A Poisonous Appointment"),
    LocationName.apa_min2: LocationData(base_location_id + 131, "A Poisonous Appointment"),
    LocationName.apa_min3: LocationData(base_location_id + 132, "A Poisonous Appointment"),
    LocationName.apa_min4: LocationData(base_location_id + 133, "A Poisonous Appointment"),
    LocationName.apa_min5: LocationData(base_location_id + 134, "A Poisonous Appointment"),
    LocationName.apa_min6: LocationData(base_location_id + 135, "A Poisonous Appointment: Freeplay"),
    LocationName.apa_min7: LocationData(base_location_id + 136, "A Poisonous Appointment: Freeplay"),
    LocationName.apa_min8: LocationData(base_location_id + 137, "A Poisonous Appointment: Freeplay"),
    LocationName.apa_min9: LocationData(base_location_id + 138, "A Poisonous Appointment: Freeplay"),
    LocationName.apa_min10: LocationData(base_location_id + 139, "A Poisonous Appointment: Freeplay"),
    # The Face-Off
    LocationName.tfo_min1: LocationData(base_location_id + 140, "The Face-Off"),
    LocationName.tfo_min2: LocationData(base_location_id + 141, "The Face-Off"),
    LocationName.tfo_min3: LocationData(base_location_id + 142, "The Face-Off"),
    LocationName.tfo_min4: LocationData(base_location_id + 143, "The Face-Off"),
    LocationName.tfo_min5: LocationData(base_location_id + 144, "The Face-Off"),
    LocationName.tfo_min6: LocationData(base_location_id + 145, "The Face-Off"),
    LocationName.tfo_min7: LocationData(base_location_id + 146, "The Face-Off"),
    LocationName.tfo_min8: LocationData(base_location_id + 147, "The Face-Off"),
    LocationName.tfo_min9: LocationData(base_location_id + 148, "The Face-Off"),
    LocationName.tfo_min10: LocationData(base_location_id + 149, "The Face-Off"),
    # There She Goes Again
    LocationName.tsga_min1: LocationData(base_location_id + 150, "There She Goes Again"),
    LocationName.tsga_min2: LocationData(base_location_id + 151, "There She Goes Again"),
    LocationName.tsga_min3: LocationData(base_location_id + 152, "There She Goes Again"),
    LocationName.tsga_min4: LocationData(base_location_id + 153, "There She Goes Again"),
    LocationName.tsga_min5: LocationData(base_location_id + 154, "There She Goes Again"),
    LocationName.tsga_min6: LocationData(base_location_id + 155, "There She Goes Again: Freeplay"),
    LocationName.tsga_min7: LocationData(base_location_id + 156, "There She Goes Again: Freeplay"),
    LocationName.tsga_min8: LocationData(base_location_id + 157, "There She Goes Again: Freeplay"),
    LocationName.tsga_min9: LocationData(base_location_id + 158, "There She Goes Again: Freeplay"),
    LocationName.tsga_min10: LocationData(base_location_id + 159, "There She Goes Again: Freeplay"),
    # Batboat Battle
    LocationName.bbb_min1: LocationData(base_location_id + 160, "Batboat Battle"),
    LocationName.bbb_min2: LocationData(base_location_id + 161, "Batboat Battle"),
    LocationName.bbb_min3: LocationData(base_location_id + 162, "Batboat Battle"),
    LocationName.bbb_min4: LocationData(base_location_id + 163, "Batboat Battle"),
    LocationName.bbb_min5: LocationData(base_location_id + 164, "Batboat Battle"),
    LocationName.bbb_min6: LocationData(base_location_id + 165, "Batboat Battle"),
    LocationName.bbb_min7: LocationData(base_location_id + 166, "Batboat Battle"),
    LocationName.bbb_min8: LocationData(base_location_id + 167, "Batboat Battle"),
    LocationName.bbb_min9: LocationData(base_location_id + 168, "Batboat Battle"),
    LocationName.bbb_min10: LocationData(base_location_id + 169, "Batboat Battle"),
    # Under the City
    LocationName.utc_min1: LocationData(base_location_id + 170, "Under the City"),
    LocationName.utc_min2: LocationData(base_location_id + 171, "Under the City"),
    LocationName.utc_min3: LocationData(base_location_id + 172, "Under the City"),
    LocationName.utc_min4: LocationData(base_location_id + 173, "Under the City"),
    LocationName.utc_min5: LocationData(base_location_id + 174, "Under the City"),
    LocationName.utc_min6: LocationData(base_location_id + 175, "Under the City"),
    LocationName.utc_min7: LocationData(base_location_id + 176, "Under the City"),
    LocationName.utc_min8: LocationData(base_location_id + 177, "Under the City"),
    LocationName.utc_min9: LocationData(base_location_id + 178, "Under the City"),
    LocationName.utc_min10: LocationData(base_location_id + 179, "Under the City"),
    # Zoo's Company
    LocationName.zc_min1: LocationData(base_location_id + 180, "Zoo's Company"),
    LocationName.zc_min2: LocationData(base_location_id + 181, "Zoo's Company"),
    LocationName.zc_min3: LocationData(base_location_id + 182, "Zoo's Company"),
    LocationName.zc_min4: LocationData(base_location_id + 183, "Zoo's Company"),
    LocationName.zc_min5: LocationData(base_location_id + 184, "Zoo's Company"),
    LocationName.zc_min6: LocationData(base_location_id + 185, "Zoo's Company"),
    LocationName.zc_min7: LocationData(base_location_id + 186, "Zoo's Company"),
    LocationName.zc_min8: LocationData(base_location_id + 187, "Zoo's Company"),
    LocationName.zc_min9: LocationData(base_location_id + 188, "Zoo's Company"),
    LocationName.zc_min10: LocationData(base_location_id + 189, "Zoo's Company"),
    # Penguin's Lair
    LocationName.pl_min1: LocationData(base_location_id + 190, "Penguin's Lair"),
    LocationName.pl_min2: LocationData(base_location_id + 191, "Penguin's Lair"),
    LocationName.pl_min3: LocationData(base_location_id + 192, "Penguin's Lair"),
    LocationName.pl_min4: LocationData(base_location_id + 193, "Penguin's Lair"),
    LocationName.pl_min5: LocationData(base_location_id + 194, "Penguin's Lair"),
    LocationName.pl_min6: LocationData(base_location_id + 195, "Penguin's Lair"),
    LocationName.pl_min7: LocationData(base_location_id + 196, "Penguin's Lair"),
    LocationName.pl_min8: LocationData(base_location_id + 197, "Penguin's Lair"),
    LocationName.pl_min9: LocationData(base_location_id + 198, "Penguin's Lair"),
    LocationName.pl_min10: LocationData(base_location_id + 199, "Penguin's Lair"),
    # Joker's Home Turf
    LocationName.jht_min1: LocationData(base_location_id + 200, "Joker's Home Turf"),
    LocationName.jht_min2: LocationData(base_location_id + 201, "Joker's Home Turf"),
    LocationName.jht_min3: LocationData(base_location_id + 202, "Joker's Home Turf"),
    LocationName.jht_min4: LocationData(base_location_id + 203, "Joker's Home Turf"),
    LocationName.jht_min5: LocationData(base_location_id + 204, "Joker's Home Turf"),
    LocationName.jht_min6: LocationData(base_location_id + 205, "Joker's Home Turf"),
    LocationName.jht_min7: LocationData(base_location_id + 206, "Joker's Home Turf"),
    LocationName.jht_min8: LocationData(base_location_id + 207, "Joker's Home Turf"),
    LocationName.jht_min9: LocationData(base_location_id + 208, "Joker's Home Turf"),
    LocationName.jht_min10: LocationData(base_location_id + 209, "Joker's Home Turf"),
    # Little Fun at the Big Top
    LocationName.lfabt_min1: LocationData(base_location_id + 210, "Little Fun at the Big Top"),
    LocationName.lfabt_min2: LocationData(base_location_id + 211, "Little Fun at the Big Top"),
    LocationName.lfabt_min3: LocationData(base_location_id + 212, "Little Fun at the Big Top"),
    LocationName.lfabt_min4: LocationData(base_location_id + 213, "Little Fun at the Big Top"),
    LocationName.lfabt_min5: LocationData(base_location_id + 214, "Little Fun at the Big Top"),
    LocationName.lfabt_min6: LocationData(base_location_id + 215, "Little Fun at the Big Top"),
    LocationName.lfabt_min7: LocationData(base_location_id + 216, "Little Fun at the Big Top"),
    LocationName.lfabt_min8: LocationData(base_location_id + 217, "Little Fun at the Big Top"),
    LocationName.lfabt_min9: LocationData(base_location_id + 218, "Little Fun at the Big Top"),
    LocationName.lfabt_min10: LocationData(base_location_id + 219, "Little Fun at the Big Top"),
    # Flight of the Bat
    LocationName.fotb_min1: LocationData(base_location_id + 220, "Flight of the Bat"),
    LocationName.fotb_min2: LocationData(base_location_id + 221, "Flight of the Bat"),
    LocationName.fotb_min3: LocationData(base_location_id + 222, "Flight of the Bat"),
    LocationName.fotb_min4: LocationData(base_location_id + 223, "Flight of the Bat"),
    LocationName.fotb_min5: LocationData(base_location_id + 224, "Flight of the Bat"),
    LocationName.fotb_min6: LocationData(base_location_id + 225, "Flight of the Bat"),
    LocationName.fotb_min7: LocationData(base_location_id + 226, "Flight of the Bat"),
    LocationName.fotb_min8: LocationData(base_location_id + 227, "Flight of the Bat"),
    LocationName.fotb_min9: LocationData(base_location_id + 228, "Flight of the Bat"),
    LocationName.fotb_min10: LocationData(base_location_id + 229, "Flight of the Bat"),
    # In the Dark Night
    LocationName.itdn_min1: LocationData(base_location_id + 230, "In the Dark Night"),
    LocationName.itdn_min2: LocationData(base_location_id + 231, "In the Dark Night"),
    LocationName.itdn_min3: LocationData(base_location_id + 232, "In the Dark Night"),
    LocationName.itdn_min4: LocationData(base_location_id + 233, "In the Dark Night"),
    LocationName.itdn_min5: LocationData(base_location_id + 234, "In the Dark Night"),
    LocationName.itdn_min6: LocationData(base_location_id + 235, "In the Dark Night"),
    LocationName.itdn_min7: LocationData(base_location_id + 236, "In the Dark Night"),
    LocationName.itdn_min8: LocationData(base_location_id + 237, "In the Dark Night"),
    LocationName.itdn_min9: LocationData(base_location_id + 238, "In the Dark Night"),
    LocationName.itdn_min10: LocationData(base_location_id + 239, "In the Dark Night"),
    # To the Top of the Tower
    LocationName.tttot_min1: LocationData(base_location_id + 240, "To the Top of the Tower"),
    LocationName.tttot_min2: LocationData(base_location_id + 241, "To the Top of the Tower"),
    LocationName.tttot_min3: LocationData(base_location_id + 242, "To the Top of the Tower"),
    LocationName.tttot_min4: LocationData(base_location_id + 243, "To the Top of the Tower"),
    LocationName.tttot_min5: LocationData(base_location_id + 244, "To the Top of the Tower"),
    LocationName.tttot_min6: LocationData(base_location_id + 245, "To the Top of the Tower"),
    LocationName.tttot_min7: LocationData(base_location_id + 246, "To the Top of the Tower"),
    LocationName.tttot_min8: LocationData(base_location_id + 247, "To the Top of the Tower"),
    LocationName.tttot_min9: LocationData(base_location_id + 248, "To the Top of the Tower"),
    LocationName.tttot_min10: LocationData(base_location_id + 249, "To the Top of the Tower"),
    # The Riddler Makes a Withdrawal
    LocationName.trmaw_min1: LocationData(base_location_id + 250, "The Riddler Makes a Withdrawal"),
    LocationName.trmaw_min2: LocationData(base_location_id + 251, "The Riddler Makes a Withdrawal"),
    LocationName.trmaw_min3: LocationData(base_location_id + 252, "The Riddler Makes a Withdrawal"),
    LocationName.trmaw_min4: LocationData(base_location_id + 253, "The Riddler Makes a Withdrawal: Freeplay"),
    LocationName.trmaw_min5: LocationData(base_location_id + 254, "The Riddler Makes a Withdrawal: Freeplay"),
    LocationName.trmaw_min6: LocationData(base_location_id + 255, "The Riddler Makes a Withdrawal: Freeplay"),
    LocationName.trmaw_min7: LocationData(base_location_id + 256, "The Riddler Makes a Withdrawal"),
    LocationName.trmaw_min8: LocationData(base_location_id + 257, "The Riddler Makes a Withdrawal"),
    LocationName.trmaw_min9: LocationData(base_location_id + 258, "The Riddler Makes a Withdrawal: Freeplay"),
    LocationName.trmaw_min10: LocationData(base_location_id + 259, "The Riddler Makes a Withdrawal"),
    # On the Rocks
    LocationName.otr_min1: LocationData(base_location_id + 260, "On the Rocks"),
    LocationName.otr_min2: LocationData(base_location_id + 261, "On the Rocks"),
    LocationName.otr_min3: LocationData(base_location_id + 262, "On the Rocks"),
    LocationName.otr_min4: LocationData(base_location_id + 263, "On the Rocks: Freeplay"),
    LocationName.otr_min5: LocationData(base_location_id + 264, "On the Rocks: Freeplay"),
    LocationName.otr_min6: LocationData(base_location_id + 265, "On the Rocks"),
    LocationName.otr_min7: LocationData(base_location_id + 266, "On the Rocks: Freeplay"),
    LocationName.otr_min8: LocationData(base_location_id + 267, "On the Rocks: Freeplay"),
    LocationName.otr_min9: LocationData(base_location_id + 268, "On the Rocks: Freeplay"),
    LocationName.otr_min10: LocationData(base_location_id + 269, "On the Rocks"),
    # Green Fingers
    LocationName.gf_min1: LocationData(base_location_id + 270, "Green Fingers"),
    LocationName.gf_min2: LocationData(base_location_id + 271, "Green Fingers"),
    LocationName.gf_min3: LocationData(base_location_id + 272, "Green Fingers"),
    LocationName.gf_min4: LocationData(base_location_id + 273, "Green Fingers: Freeplay"),
    LocationName.gf_min5: LocationData(base_location_id + 274, "Green Fingers: Freeplay"),
    LocationName.gf_min6: LocationData(base_location_id + 275, "Green Fingers: Freeplay"),
    LocationName.gf_min7: LocationData(base_location_id + 276, "Green Fingers: Freeplay"),
    LocationName.gf_min8: LocationData(base_location_id + 277, "Green Fingers: Freeplay"),
    LocationName.gf_min9: LocationData(base_location_id + 278, "Green Fingers: Freeplay"),
    LocationName.gf_min10: LocationData(base_location_id + 279, "Green Fingers: Freeplay"),
    # An Enterprising Theft
    LocationName.aet_min1: LocationData(base_location_id + 280, "An Enterprising Theft"),
    LocationName.aet_min2: LocationData(base_location_id + 281, "An Enterprising Theft"),
    LocationName.aet_min3: LocationData(base_location_id + 282, "An Enterprising Theft"),
    LocationName.aet_min4: LocationData(base_location_id + 283, "An Enterprising Theft"),
    LocationName.aet_min5: LocationData(base_location_id + 284, "An Enterprising Theft"),
    LocationName.aet_min6: LocationData(base_location_id + 285, "An Enterprising Theft"),
    LocationName.aet_min7: LocationData(base_location_id + 286, "An Enterprising Theft"),
    LocationName.aet_min8: LocationData(base_location_id + 287, "An Enterprising Theft"),
    LocationName.aet_min9: LocationData(base_location_id + 288, "An Enterprising Theft"),
    LocationName.aet_min10: LocationData(base_location_id + 289, "An Enterprising Theft"),
    # Breaking Blocks
    LocationName.bb_min1: LocationData(base_location_id + 290, "Breaking Blocks"),
    LocationName.bb_min2: LocationData(base_location_id + 291, "Breaking Blocks: Freeplay"),
    LocationName.bb_min3: LocationData(base_location_id + 292, "Breaking Blocks: Freeplay"),
    LocationName.bb_min4: LocationData(base_location_id + 293, "Breaking Blocks: Freeplay"),
    LocationName.bb_min5: LocationData(base_location_id + 294, "Breaking Blocks: Freeplay"),
    LocationName.bb_min6: LocationData(base_location_id + 295, "Breaking Blocks: Freeplay"),
    LocationName.bb_min7: LocationData(base_location_id + 296, "Breaking Blocks: Freeplay"),
    LocationName.bb_min8: LocationData(base_location_id + 297, "Breaking Blocks: Freeplay"),
    LocationName.bb_min9: LocationData(base_location_id + 298, "Breaking Blocks: Freeplay"),
    LocationName.bb_min10: LocationData(base_location_id + 299, "Breaking Blocks: Freeplay"),
    # Rockin' the Docks
    LocationName.rtd_min1: LocationData(base_location_id + 300, "Rockin' the Docks: Freeplay"),
    LocationName.rtd_min2: LocationData(base_location_id + 301, "Rockin' the Docks: Freeplay"),
    LocationName.rtd_min3: LocationData(base_location_id + 302, "Rockin' the Docks"),
    LocationName.rtd_min4: LocationData(base_location_id + 303, "Rockin' the Docks"),
    LocationName.rtd_min5: LocationData(base_location_id + 304, "Rockin' the Docks: Freeplay"),
    LocationName.rtd_min6: LocationData(base_location_id + 305, "Rockin' the Docks"),
    LocationName.rtd_min7: LocationData(base_location_id + 306, "Rockin' the Docks: Freeplay"),
    LocationName.rtd_min8: LocationData(base_location_id + 307, "Rockin' the Docks"),
    LocationName.rtd_min9: LocationData(base_location_id + 308, "Rockin' the Docks: Freeplay"),
    LocationName.rtd_min10: LocationData(base_location_id + 309, "Rockin' the Docks"),
    # Stealing the Show
    LocationName.sts_min1: LocationData(base_location_id + 310, "Stealing the Show"),
    LocationName.sts_min2: LocationData(base_location_id + 311, "Stealing the Show"),
    LocationName.sts_min3: LocationData(base_location_id + 312, "Stealing the Show"),
    LocationName.sts_min4: LocationData(base_location_id + 313, "Stealing the Show"),
    LocationName.sts_min5: LocationData(base_location_id + 314, "Stealing the Show"),
    LocationName.sts_min6: LocationData(base_location_id + 315, "Stealing the Show: Freeplay"),
    LocationName.sts_min7: LocationData(base_location_id + 316, "Stealing the Show: Freeplay"),
    LocationName.sts_min8: LocationData(base_location_id + 317, "Stealing the Show"),
    LocationName.sts_min9: LocationData(base_location_id + 318, "Stealing the Show: Freeplay"),
    LocationName.sts_min10: LocationData(base_location_id + 319, "Stealing the Show: Freeplay"),
    # Harbouring a Grudge
    LocationName.hag_min1: LocationData(base_location_id + 320, "Harbouring a Grudge"),
    LocationName.hag_min2: LocationData(base_location_id + 321, "Harbouring a Grudge"),
    LocationName.hag_min3: LocationData(base_location_id + 322, "Harbouring a Grudge: Freeplay"),
    LocationName.hag_min4: LocationData(base_location_id + 323, "Harbouring a Grudge"),
    LocationName.hag_min5: LocationData(base_location_id + 324, "Harbouring a Grudge"),
    LocationName.hag_min6: LocationData(base_location_id + 325, "Harbouring a Grudge"),
    LocationName.hag_min7: LocationData(base_location_id + 326, "Harbouring a Grudge"),
    LocationName.hag_min8: LocationData(base_location_id + 327, "Harbouring a Grudge: Freeplay"),
    LocationName.hag_min9: LocationData(base_location_id + 328, "Harbouring a Grudge"),
    LocationName.hag_min10: LocationData(base_location_id + 329, "Harbouring a Grudge: Freeplay"),
    # A Daring Rescue
    LocationName.adr_min1: LocationData(base_location_id + 330, "A Daring Rescue"),
    LocationName.adr_min2: LocationData(base_location_id + 331, "A Daring Rescue: Freeplay"),
    LocationName.adr_min3: LocationData(base_location_id + 332, "A Daring Rescue: Freeplay"),
    LocationName.adr_min4: LocationData(base_location_id + 333, "A Daring Rescue"),
    LocationName.adr_min5: LocationData(base_location_id + 334, "A Daring Rescue: Freeplay"),
    LocationName.adr_min6: LocationData(base_location_id + 335, "A Daring Rescue: Freeplay"),
    LocationName.adr_min7: LocationData(base_location_id + 336, "A Daring Rescue: Freeplay"),
    LocationName.adr_min8: LocationData(base_location_id + 337, "A Daring Rescue"),
    LocationName.adr_min9: LocationData(base_location_id + 338, "A Daring Rescue: Freeplay"),
    LocationName.adr_min10: LocationData(base_location_id + 339, "A Daring Rescue"),
    # Arctic World
    LocationName.aw_min1: LocationData(base_location_id + 340, "Arctic World"),
    LocationName.aw_min2: LocationData(base_location_id + 341, "Arctic World"),
    LocationName.aw_min3: LocationData(base_location_id + 342, "Arctic World"),
    LocationName.aw_min4: LocationData(base_location_id + 343, "Arctic World"),
    LocationName.aw_min5: LocationData(base_location_id + 344, "Arctic World: Freeplay"),
    LocationName.aw_min6: LocationData(base_location_id + 345, "Arctic World"),
    LocationName.aw_min7: LocationData(base_location_id + 346, "Arctic World: Freeplay"),
    LocationName.aw_min8: LocationData(base_location_id + 347, "Arctic World: Freeplay"),
    LocationName.aw_min9: LocationData(base_location_id + 348, "Arctic World: Freeplay"),
    LocationName.aw_min10: LocationData(base_location_id + 349, "Arctic World: Freeplay"),
    # A Surprise for the Commissioner
    LocationName.asftc_min1: LocationData(base_location_id + 350, "A Surprise for the Commissioner: Freeplay"),
    LocationName.asftc_min2: LocationData(base_location_id + 351, "A Surprise for the Commissioner: Freeplay"),
    LocationName.asftc_min3: LocationData(base_location_id + 352, "A Surprise for the Commissioner: Freeplay"),
    LocationName.asftc_min4: LocationData(base_location_id + 353, "A Surprise for the Commissioner: Freeplay"),
    LocationName.asftc_min5: LocationData(base_location_id + 354, "A Surprise for the Commissioner: Freeplay"),
    LocationName.asftc_min6: LocationData(base_location_id + 355, "A Surprise for the Commissioner"),
    LocationName.asftc_min7: LocationData(base_location_id + 356, "A Surprise for the Commissioner: Freeplay"),
    LocationName.asftc_min8: LocationData(base_location_id + 357, "A Surprise for the Commissioner: Freeplay"),
    LocationName.asftc_min9: LocationData(base_location_id + 358, "A Surprise for the Commissioner: Freeplay"),
    LocationName.asftc_min10: LocationData(base_location_id + 359, "A Surprise for the Commissioner"),
    # Biplane Blast
    LocationName.bbpl_min1: LocationData(base_location_id + 360, "Biplane Blast: Freeplay"),
    LocationName.bbpl_min2: LocationData(base_location_id + 361, "Biplane Blast"),
    LocationName.bbpl_min3: LocationData(base_location_id + 362, "Biplane Blast: Freeplay"),
    LocationName.bbpl_min4: LocationData(base_location_id + 363, "Biplane Blast"),
    LocationName.bbpl_min5: LocationData(base_location_id + 364, "Biplane Blast"),
    LocationName.bbpl_min6: LocationData(base_location_id + 365, "Biplane Blast"),
    LocationName.bbpl_min7: LocationData(base_location_id + 366, "Biplane Blast"),
    LocationName.bbpl_min8: LocationData(base_location_id + 367, "Biplane Blast: Freeplay"),
    LocationName.bbpl_min9: LocationData(base_location_id + 368, "Biplane Blast: Freeplay"),
    LocationName.bbpl_min10: LocationData(base_location_id + 369, "Biplane Blast: Freeplay"),
    # The Joker's Masterpiece
    LocationName.tjm_min1: LocationData(base_location_id + 370, "The Joker's Masterpiece"),
    LocationName.tjm_min2: LocationData(base_location_id + 371, "The Joker's Masterpiece"),
    LocationName.tjm_min3: LocationData(base_location_id + 372, "The Joker's Masterpiece: Freeplay"),
    LocationName.tjm_min4: LocationData(base_location_id + 373, "The Joker's Masterpiece"),
    LocationName.tjm_min5: LocationData(base_location_id + 374, "The Joker's Masterpiece: Freeplay"),
    LocationName.tjm_min6: LocationData(base_location_id + 375, "The Joker's Masterpiece: Freeplay"),
    LocationName.tjm_min7: LocationData(base_location_id + 376, "The Joker's Masterpiece: Freeplay"),
    LocationName.tjm_min8: LocationData(base_location_id + 377, "The Joker's Masterpiece: Freeplay"),
    LocationName.tjm_min9: LocationData(base_location_id + 378, "The Joker's Masterpiece: Freeplay"),
    LocationName.tjm_min10: LocationData(base_location_id + 379, "The Joker's Masterpiece"),
    # The Lure of the Night
    LocationName.tlotn_min1: LocationData(base_location_id + 380, "The Lure of the Night"),
    LocationName.tlotn_min2: LocationData(base_location_id + 381, "The Lure of the Night: Freeplay"),
    LocationName.tlotn_min3: LocationData(base_location_id + 382, "The Lure of the Night: Freeplay"),
    LocationName.tlotn_min4: LocationData(base_location_id + 383, "The Lure of the Night: Freeplay"),
    LocationName.tlotn_min5: LocationData(base_location_id + 384, "The Lure of the Night: Freeplay"),
    LocationName.tlotn_min6: LocationData(base_location_id + 385, "The Lure of the Night"),
    LocationName.tlotn_min7: LocationData(base_location_id + 386, "The Lure of the Night"),
    LocationName.tlotn_min8: LocationData(base_location_id + 387, "The Lure of the Night"),
    LocationName.tlotn_min9: LocationData(base_location_id + 388, "The Lure of the Night: Freeplay"),
    LocationName.tlotn_min10: LocationData(base_location_id + 389, "The Lure of the Night: Freeplay"),
    # Dying of Laughter
    LocationName.dol_min1: LocationData(base_location_id + 390, "Dying of Laughter"),
    LocationName.dol_min2: LocationData(base_location_id + 391, "Dying of Laughter"),
    LocationName.dol_min3: LocationData(base_location_id + 392, "Dying of Laughter"),
    LocationName.dol_min4: LocationData(base_location_id + 393, "Dying of Laughter: Freeplay"),
    LocationName.dol_min5: LocationData(base_location_id + 394, "Dying of Laughter: Freeplay"),
    LocationName.dol_min6: LocationData(base_location_id + 395, "Dying of Laughter: Freeplay"),
    LocationName.dol_min7: LocationData(base_location_id + 396, "Dying of Laughter: Freeplay"),
    LocationName.dol_min8: LocationData(base_location_id + 397, "Dying of Laughter: Freeplay"),
    LocationName.dol_min9: LocationData(base_location_id + 398, "Dying of Laughter"),
    LocationName.dol_min10: LocationData(base_location_id + 399, "Dying of Laughter: Freeplay"),
}

hostage_location_table: Dict[str, LocationData] = {
    LocationName.ycbob_host: LocationData(base_location_id + 400, "You can Bank on Batman"),
    LocationName.air_host: LocationData(base_location_id + 401, "An Icy Reception"),
    LocationName.apa_host: LocationData(base_location_id + 402, "A Poisonous Appointment"),
    LocationName.tfo_host: LocationData(base_location_id + 403, "The Face-Off"),
    LocationName.tsga_host: LocationData(base_location_id + 404, "There She Goes Again: Freeplay"),
    LocationName.utc_host: LocationData(base_location_id + 405, "Under the City"),
    LocationName.zc_host: LocationData(base_location_id + 406, "Zoo's Company"),
    LocationName.pl_host: LocationData(base_location_id + 407, "Penguin's Lair"),
    LocationName.jht_host: LocationData(base_location_id + 408, "Joker's Home Turf"),
    LocationName.lfabt_host: LocationData(base_location_id + 409, "Little Fun at the Big Top"),
    LocationName.itdn_host: LocationData(base_location_id + 410, "In the Dark Night"),
    LocationName.tttot_host: LocationData(base_location_id + 411, "To the Top of the Tower"),
    LocationName.trmaw_host: LocationData(base_location_id + 412, "The Riddler Makes a Withdrawal: Freeplay"),
    LocationName.otr_host: LocationData(base_location_id + 413, "On the Rocks: Freeplay"),
    LocationName.gf_host: LocationData(base_location_id + 414, "Green Fingers"),
    LocationName.aet_host: LocationData(base_location_id + 415, "An Enterprising Theft"),
    LocationName.bb_host: LocationData(base_location_id + 416, "Breaking Blocks: Freeplay"),
    LocationName.rtd_host: LocationData(base_location_id + 417, "Rockin' the Docks: Freeplay"),
    LocationName.sts_host: LocationData(base_location_id + 418, "Stealing the Show"),
    LocationName.adr_host: LocationData(base_location_id + 419, "A Daring Rescue: Freeplay"),
    LocationName.aw_host: LocationData(base_location_id + 420, "Arctic World"),
    LocationName.asftc_host: LocationData(base_location_id + 421, "A Surprise for the Commissioner: Freeplay"),
    LocationName.tjm_host: LocationData(base_location_id + 422, "The Joker's Masterpiece"),
    LocationName.tlotn_host: LocationData(base_location_id + 423, "The Lure of the Night: Freeplay"),
    LocationName.dol_host: LocationData(base_location_id + 424, "Dying of Laughter: Freeplay"),
}

level_beaten_location_table: Dict[str, LocationData] = {
    LocationName.ycbob_beat: LocationData(base_location_id + 425, "You can Bank on Batman"),
    LocationName.air_beat: LocationData(base_location_id + 426, "An Icy Reception"),
    LocationName.tfc_beat: LocationData(base_location_id + 427, "Two-Face Chase"),
    LocationName.apa_beat: LocationData(base_location_id + 428, "A Poisonous Appointment"),
    LocationName.tfo_beat: LocationData(base_location_id + 429, "The Face-Off"),
    LocationName.tsga_beat: LocationData(base_location_id + 430, "There She Goes Again: Freeplay"),
    LocationName.bbb_beat: LocationData(base_location_id + 431, "Batboat Battle"),
    LocationName.utc_beat: LocationData(base_location_id + 432, "Under the City"),
    LocationName.zc_beat: LocationData(base_location_id + 433, "Zoo's Company"),
    LocationName.pl_beat: LocationData(base_location_id + 434, "Penguin's Lair"),
    LocationName.jht_beat: LocationData(base_location_id + 435, "Joker's Home Turf"),
    LocationName.lfabt_beat: LocationData(base_location_id + 436, "Little Fun at the Big Top"),
    LocationName.fotb_beat: LocationData(base_location_id + 437, "Flight of the Bat"),
    LocationName.itdn_beat: LocationData(base_location_id + 438, "In the Dark Night"),
    LocationName.tttot_beat: LocationData(base_location_id + 439, "To the Top of the Tower"),
    LocationName.trmaw_beat: LocationData(base_location_id + 440, "The Riddler Makes a Withdrawal"),
    LocationName.otr_beat: LocationData(base_location_id + 441, "On the Rocks"),
    LocationName.gf_beat: LocationData(base_location_id + 442, "Green Fingers"),
    LocationName.aet_beat: LocationData(base_location_id + 443, "An Enterprising Theft"),
    LocationName.bb_beat: LocationData(base_location_id + 444, "Breaking Blocks"),
    LocationName.rtd_beat: LocationData(base_location_id + 445, "Rockin' the Docks"),
    LocationName.sts_beat: LocationData(base_location_id + 446, "Stealing the Show"),
    LocationName.hag_beat: LocationData(base_location_id + 447, "Harbouring a Grudge"),
    LocationName.adr_beat: LocationData(base_location_id + 448, "A Daring Rescue"),
    LocationName.aw_beat: LocationData(base_location_id + 449, "Arctic World"),
    LocationName.asftc_beat: LocationData(base_location_id + 450, "A Surprise for the Commissioner"),
    LocationName.bbpl_beat: LocationData(base_location_id + 451, "Biplane Blast"),
    LocationName.tjm_beat: LocationData(base_location_id + 452, "The Joker's Masterpiece"),
    LocationName.tlotn_beat: LocationData(base_location_id + 453, "The Lure of the Night"),
    LocationName.dol_beat: LocationData(base_location_id + 454, "Dying of Laughter"),
}

true_status_location_table: Dict[str, LocationData] = {
    LocationName.ycbob_ts: LocationData(base_location_id + 455, "You can Bank on Batman"),
    LocationName.air_ts: LocationData(base_location_id + 456, "An Icy Reception"),
    LocationName.tfc_ts: LocationData(base_location_id + 457, "Two-Face Chase"),
    LocationName.apa_ts: LocationData(base_location_id + 458, "A Poisonous Appointment"),
    LocationName.tfo_ts: LocationData(base_location_id + 459, "The Face-Off"),
    LocationName.tsga_ts: LocationData(base_location_id + 460, "There She Goes Again"),
    LocationName.bbb_ts: LocationData(base_location_id + 461, "Batboat Battle"),
    LocationName.utc_ts: LocationData(base_location_id + 462, "Under the City"),
    LocationName.zc_ts: LocationData(base_location_id + 463, "Zoo's Company"),
    LocationName.pl_ts: LocationData(base_location_id + 464, "Penguin's Lair"),
    LocationName.jht_ts: LocationData(base_location_id + 465, "Joker's Home Turf"),
    LocationName.lfabt_ts: LocationData(base_location_id + 466, "Little Fun at the Big Top"),
    LocationName.fotb_ts: LocationData(base_location_id + 467, "Flight of the Bat"),
    LocationName.itdn_ts: LocationData(base_location_id + 468, "In the Dark Night"),
    LocationName.tttot_ts: LocationData(base_location_id + 469, "To the Top of the Tower"),
    LocationName.trmaw_ts: LocationData(base_location_id + 470, "The Riddler Makes a Withdrawal"),
    LocationName.otr_ts: LocationData(base_location_id + 471, "On the Rocks"),
    LocationName.gf_ts: LocationData(base_location_id + 472, "Green Fingers"),
    LocationName.aet_ts: LocationData(base_location_id + 473, "An Enterprising Theft"),
    LocationName.bb_ts: LocationData(base_location_id + 474, "Breaking Blocks"),
    LocationName.rtd_ts: LocationData(base_location_id + 475, "Rockin' the Docks"),
    LocationName.sts_ts: LocationData(base_location_id + 476, "Stealing the Show"),
    LocationName.hag_ts: LocationData(base_location_id + 477, "Harbouring a Grudge"),
    LocationName.adr_ts: LocationData(base_location_id + 478, "A Daring Rescue"),
    LocationName.aw_ts: LocationData(base_location_id + 479, "Arctic World"),
    LocationName.asftc_ts: LocationData(base_location_id + 480, "A Surprise for the Commissioner"),
    LocationName.bbpl_ts: LocationData(base_location_id + 481, "Biplane Blast"),
    LocationName.tjm_ts: LocationData(base_location_id + 482, "The Joker's Masterpiece"),
    LocationName.tlotn_ts: LocationData(base_location_id + 483, "The Lure of the Night"),
    LocationName.dol_ts: LocationData(base_location_id + 484, "Dying of Laughter"),
}

red_brick_location_table = {
    LocationName.ycbob_rb: LocationData(base_location_id + 485, "You can Bank on Batman: Freeplay"),
    LocationName.air_rb: LocationData(base_location_id + 486, "An Icy Reception: Freeplay"),
    LocationName.tfc_rb: LocationData(base_location_id + 487, "Two-Face Chase"),
    LocationName.apa_rb: LocationData(base_location_id + 488, "A Poisonous Appointment: Freeplay"),
    LocationName.tfo_rb: LocationData(base_location_id + 489, "The Face-Off"),
    LocationName.tsga_rb: LocationData(base_location_id + 490, "There She Goes Again: Freeplay"),
    LocationName.bbb_rb: LocationData(base_location_id + 491, "Batboat Battle"),
    LocationName.utc_rb: LocationData(base_location_id + 492, "Under the City"),
    LocationName.zc_rb: LocationData(base_location_id + 493, "Zoo's Company"),
    LocationName.pl_rb: LocationData(base_location_id + 494, "Penguin's Lair"),
    LocationName.jht_rb: LocationData(base_location_id + 495, "Joker's Home Turf"),
    LocationName.lfabt_rb: LocationData(base_location_id + 496, "Little Fun at the Big Top"),
    LocationName.fotb_rb: LocationData(base_location_id + 497, "Flight of the Bat"),
    LocationName.itdn_rb: LocationData(base_location_id + 498, "In the Dark Night"),
    LocationName.tttot_rb: LocationData(base_location_id + 499, "To the Top of the Tower"),
    LocationName.trmaw_rb: LocationData(base_location_id + 500, "The Riddler Makes a Withdrawal: Freeplay"),
    LocationName.otr_rb: LocationData(base_location_id + 501, "On the Rocks: Freeplay"),
    LocationName.gf_rb: LocationData(base_location_id + 502, "Green Fingers"),
    LocationName.aet_rb: LocationData(base_location_id + 503, "An Enterprising Theft"),
    LocationName.bb_rb: LocationData(base_location_id + 504, "Breaking Blocks: Freeplay"),
    LocationName.rtd_rb: LocationData(base_location_id + 505, "Rockin' the Docks: Freeplay"),
    LocationName.sts_rb: LocationData(base_location_id + 506, "Stealing the Show: Freeplay"),
    LocationName.hag_rb: LocationData(base_location_id + 507, "Harbouring a Grudge: Freeplay"),
    LocationName.adr_rb: LocationData(base_location_id + 508, "A Daring Rescue: Freeplay"),
    LocationName.aw_rb: LocationData(base_location_id + 509, "Arctic World"),
    LocationName.asftc_rb: LocationData(base_location_id + 510, "A Surprise for the Commissioner: Freeplay"),
    LocationName.bbpl_rb: LocationData(base_location_id + 511, "Biplane Blast"),
    LocationName.tjm_rb: LocationData(base_location_id + 512, "The Joker's Masterpiece"),
    LocationName.tlotn_rb: LocationData(base_location_id + 513, "The Lure of the Night: Freeplay"),
    LocationName.dol_rb: LocationData(base_location_id + 514, "Dying of Laughter"),
}

red_brick_purchase_table = {
    LocationName.silhouettes: LocationData(base_location_id + 515, "Shop"),
    LocationName.beepbeep: LocationData(base_location_id + 516, "Shop"),
    LocationName.icerink: LocationData(base_location_id + 517, "Shop"),
    LocationName.disguise: LocationData(base_location_id + 518, "Shop"),
    LocationName.extratoggle: LocationData(base_location_id + 519, "Shop"),
    LocationName.scorex2: LocationData(base_location_id + 520, "Shop"),
    LocationName.scorex4: LocationData(base_location_id + 521, "Shop"),
    LocationName.scorex6: LocationData(base_location_id + 522, "Shop"),
    LocationName.scorex8: LocationData(base_location_id + 523, "Shop"),
    LocationName.scorex10: LocationData(base_location_id + 524, "Shop"),
    LocationName.studmagnet: LocationData(base_location_id + 525, "Shop"),
    LocationName.charstuds: LocationData(base_location_id + 526, "Shop"),
    LocationName.minikitdetect: LocationData(base_location_id + 527, "Shop"),
    LocationName.pwrbrickdetect: LocationData(base_location_id + 528, "Shop"),
    LocationName.alwaysscore: LocationData(base_location_id + 529, "Shop"),
    LocationName.fastbuild: LocationData(base_location_id + 530, "Shop"),
    LocationName.immunefreeze: LocationData(base_location_id + 531, "Shop"),
    LocationName.regenhearts: LocationData(base_location_id + 532, "Shop"),
    LocationName.extrahearts: LocationData(base_location_id + 533, "Shop"),
    LocationName.invincibility: LocationData(base_location_id + 534, "Shop"),
    LocationName.fastgrapple: LocationData(base_location_id + 535, "Shop"),
    LocationName.fastbatarang: LocationData(base_location_id + 536, "Shop"),
    LocationName.moretargets: LocationData(base_location_id + 537, "Shop"),
    LocationName.flamingbata: LocationData(base_location_id + 538, "Shop"),
    LocationName.slam: LocationData(base_location_id + 539, "Shop"),
    LocationName.moredet: LocationData(base_location_id + 540, "Shop"),
    LocationName.armorplating: LocationData(base_location_id + 541, "Shop"),
    LocationName.sonicpain: LocationData(base_location_id + 542, "Shop"),
    LocationName.areaeffect: LocationData(base_location_id + 543, "Shop"),
    LocationName.bats: LocationData(base_location_id + 544, "Shop"),
    LocationName.freezebatarang: LocationData(base_location_id + 545, "Shop"),
    LocationName.decoy: LocationData(base_location_id + 546, "Shop"),
    LocationName.fastwalk: LocationData(base_location_id + 547, "Shop"),
    LocationName.fasterpieces: LocationData(base_location_id + 548, "Shop"),
    LocationName.piecedetect: LocationData(base_location_id + 549, "Shop"),
}

level_beaten_event_location_table = {
    LocationName.ycbob_token: LocationData(0, "You can Bank on Batman"),
    LocationName.air_token: LocationData(0, "An Icy Reception"),
    LocationName.tfc_token: LocationData(0, "Two-Face Chase"),
    LocationName.apa_token: LocationData(0, "A Poisonous Appointment"),
    LocationName.tfo_token: LocationData(0, "The Face-Off"),
    LocationName.tsga_token: LocationData(0, "There She Goes Again"),
    LocationName.bbb_token: LocationData(0, "Batboat Battle"),
    LocationName.utc_token: LocationData(0, "Under the City"),
    LocationName.zc_token: LocationData(0, "Zoo's Company"),
    LocationName.pl_token: LocationData(0, "Penguin's Lair"),
    LocationName.jht_token: LocationData(0, "Joker's Home Turf"),
    LocationName.lfabt_token: LocationData(0, "Little Fun at the Big Top"),
    LocationName.fotb_token: LocationData(0, "Flight of the Bat"),
    LocationName.itdn_token: LocationData(0, "In the Dark Night"),
    LocationName.tttot_token: LocationData(0, "To the Top of the Tower"),
    LocationName.trmaw_token: LocationData(0, "The Riddler Makes a Withdrawal"),
    LocationName.otr_token: LocationData(0, "On the Rocks"),
    LocationName.gf_token: LocationData(0, "Green Fingers"),
    LocationName.aet_token: LocationData(0, "An Enterprising Theft"),
    LocationName.bb_token: LocationData(0, "Breaking Blocks"),
    LocationName.rtd_token: LocationData(0, "Rockin' the Docks"),
    LocationName.sts_token: LocationData(0, "Stealing the Show"),
    LocationName.hag_token: LocationData(0, "Harbouring a Grudge"),
    LocationName.adr_token: LocationData(0, "A Daring Rescue"),
    LocationName.aw_token: LocationData(0, "Arctic World"),
    LocationName.asftc_token: LocationData(0, "A Surprise for the Commissioner"),
    LocationName.bbpl_token: LocationData(0, "Biplane Blast"),
    LocationName.tjm_token: LocationData(0, "The Joker's Masterpiece"),
    LocationName.tlotn_token: LocationData(0, "The Lure of the Night"),
    LocationName.dol_token: LocationData(0, "Dying of Laughter"),
}

all_location_table = {
    **character_location_table,
    **hard_character_location_table,
    **automobile_location_table,
    **watercraft_location_table,
    **aircraft_location_table,
    **suit_location_table,
    **minikit_location_table,
    **hostage_location_table,
    **level_beaten_location_table,
    **true_status_location_table,
    **red_brick_location_table,
    **red_brick_purchase_table
}


def setup_locations(options: LB1Options):
    temp_location_table = {}
    if options.minikit_sanity == 1:
        temp_location_table.update({**minikit_location_table})
    if options.true_status_sanity == 1:
        temp_location_table.update({**true_status_location_table})
    temp_location_table.update({**character_location_table})
    temp_location_table.update({**hard_character_location_table})
    temp_location_table.update({**automobile_location_table})
    temp_location_table.update({**watercraft_location_table})
    temp_location_table.update({**aircraft_location_table})
    temp_location_table.update({**suit_location_table})
    temp_location_table.update({**hostage_location_table})
    temp_location_table.update({**level_beaten_location_table})
    temp_location_table.update({**red_brick_location_table})
    temp_location_table.update({**red_brick_purchase_table})
    return temp_location_table
