from BaseClasses import Location

class LB1Location(Location):
    game: str = "Lego Batman: The Videogame"


base_location_id: int = 400000

minikit_location_table: dict[str, int] = {
    "You can Bank on Batman: Minikit 1 - Inside Garage": base_location_id + 100,
    "You can Bank on Batman: Minikit 2 - Above Garage": base_location_id + 101,
    "You can Bank on Batman: Minikit 3 - Behind Glass Window near Spawn": base_location_id + 102,
    "You can Bank on Batman: Minikit 4 - Mind Control Behind Van in Toxic Waste": base_location_id + 103,
    "You can Bank on Batman: Minikit 5 - In Sewer Grate": base_location_id + 104,
    "You can Bank on Batman: Minikit 6 - In High Window by Cement Mixer": base_location_id + 105,
    "You can Bank on Batman: Minikit 7 - On Balcony Behind Heavy Item near Downward Slope": base_location_id + 106,
    "You can Bank on Batman: Minikit 8 - From Hazard Recycler": base_location_id + 107,
    "You can Bank on Batman: Minikit 9 - Park Two Cars": base_location_id + 108,
    "You can Bank on Batman: Minikit 10 - from Destroying Five Phone Booths": base_location_id + 109,

    "An Icy Reception: Minikit 1 - On Ledge near Spawn": base_location_id + 110,
    "An Icy Reception: Minikit 2 - Behind Boarded Window on Ledge near Spawn": base_location_id + 111,
    "An Icy Reception: Minikit 3 - In Silver Lego Icecream Stand": base_location_id + 112,
    "An Icy Reception: Minikit 4 - Behind Icecream Truck": base_location_id + 113,
    "An Icy Reception: Minikit 5 - In Alley with Hostage": base_location_id + 114,
    "An Icy Reception: Minikit 6 - In Silver Legos Above Icecream Cones": base_location_id + 115,
    "An Icy Reception: Minikit 7 - In Female Locked Room": base_location_id + 116,
    "An Icy Reception: Minikit 8 - In Silver Legos Behind Toxic Gas": base_location_id + 117,
    "An Icy Reception: Minikit 9 - In Vent with Fan": base_location_id + 118,
    "An Icy Reception: Minikit 10 - In Hypnosis Room": base_location_id + 119,

    "Two-Face Chase: Minikit 1 - Destroy Three Dumpsters": base_location_id + 120,
    "Two-Face Chase: Minikit 2 - In Manhole Cover": base_location_id + 121,
    "Two-Face Chase: Minikit 3 - Destroy Southwest Trash Dumpster": base_location_id + 122,
    "Two-Face Chase: Minikit 4 - Destroy Three Cars": base_location_id + 123,
    "Two-Face Chase: Minikit 5 - Destroy North Supports": base_location_id + 124,
    "Two-Face Chase: Minikit 6 - Destroy South Supports": base_location_id + 125,
    "Two-Face Chase: Minikit 7 - Use Joker's Van Panel": base_location_id + 126,
    "Two-Face Chase: Minikit 8 - Use Harley's Truck Panel": base_location_id + 127,
    "Two-Face Chase: Minikit 9 - In Telephone Booth": base_location_id + 128,
    "Two-Face Chase: Minikit 10 - Destroy Three Food Carts": base_location_id + 129,

    "A Poisonous Appointment: Minikit 1 - Destroy All Carrots": base_location_id + 130,
    "A Poisonous Appointment: Minikit 2 - On Top of Trees": base_location_id + 131,
    "A Poisonous Appointment: Minikit 3 - In Heated Greenhouse": base_location_id + 132,
    "A Poisonous Appointment: Minikit 4 - Above Orange Flowers": base_location_id + 133,
    "A Poisonous Appointment: Minikit 5 - By Rail above Potted Plant": base_location_id + 134,
    "A Poisonous Appointment: Minikit 6 - In Underwater Pipe": base_location_id + 135,
    "A Poisonous Appointment: Minikit 7 - In Vat near Second Pitcher Plant": base_location_id + 136,
    "A Poisonous Appointment: Minikit 8 - Destroy 3 Carrots": base_location_id + 137,
    "A Poisonous Appointment: Minikit 9 - Above Heated Pipes": base_location_id + 138,
    "A Poisonous Appointment: Minikit 10 - In Toxic Waste Room Above Ledge": base_location_id + 139,

    "The Face-Off: Minikit 1 - Jump on 5 Poles": base_location_id + 140,
    "The Face-Off: Minikit 2 - In Grapple Point to Right of Spawn": base_location_id + 141,
    "The Face-Off: Minikit 3 - Build Dollar Sign": base_location_id + 142,
    "The Face-Off: Minikit 4 - In Revolving Door": base_location_id + 143,
    "The Face-Off: Minikit 5 - On Roof Above Recycler": base_location_id + 144,
    "The Face-Off: Minikit 6 - In the Toxic Waste Room Pipe": base_location_id + 145,
    "The Face-Off: Minikit 7 - Underneath the Toxic Waste near the Three Platform Bridge": base_location_id + 146,
    "The Face-Off: Minikit 8 - On Right Side of Toxic Waste Room": base_location_id + 147,
    "The Face-Off: Minikit 9 - On Right Side of Vault Room": base_location_id + 148,
    "The Face-Off: Minikit 10 - Destroy Five Chests": base_location_id + 149,

    "There She Goes Again: Minikit 1 - In Female Locked Room": base_location_id + 150,
    "There She Goes Again: Minikit 2 - Drive Car Into Garage": base_location_id + 151,
    "There She Goes Again: Minikit 3 - Locked Underwater Behind Fence": base_location_id + 152,
    "There She Goes Again: Minikit 4 - Destroy Three Carrots": base_location_id + 153,
    "There She Goes Again: Minikit 5 - Locked Underwater by Blue Pump": base_location_id + 154,
    "There She Goes Again: Minikit 6 - Lawnmowing Flowers": base_location_id + 155,
    "There She Goes Again: Minikit 7 - Behind Window Above Dumpster": base_location_id + 156,
    "There She Goes Again: Minikit 8 - Behind Second Dumpster Under Water Tower": base_location_id + 157,
    "There She Goes Again: Minikit 9 - In Glass Roof": base_location_id + 158,
    "There She Goes Again: Minikit 10 - In Pipe After Breaking Glass": base_location_id + 159,

    "Batboat Battle: Minikit 1 - Turn on Lighthouse": base_location_id + 160,
    "Batboat Battle: Minikit 2 - Blow Up Silver Box": base_location_id + 161,
    "Batboat Battle: Minikit 3 - Sink the Ship": base_location_id + 162,
    "Batboat Battle: Minikit 4 - Pull the Pipe": base_location_id + 163,
    "Batboat Battle: Minikit 5 - In Alcove Surrounded by Ice": base_location_id + 164,
    "Batboat Battle: Minikit 6 - In Silver Crate Surrounded by Toxic Water": base_location_id + 165,
    "Batboat Battle: Minikit 7 - Destroy Silver Around Pipe": base_location_id + 166,
    "Batboat Battle: Minikit 8 - Destroy Three Buoys": base_location_id + 167,
    "Batboat Battle: Minikit 9 - In Corner Surrounded by Ice": base_location_id + 168,
    "Batboat Battle: Minikit 10 - Destroy Three Silver Boxes in Toxic Water": base_location_id + 169,

    "Under the City: Minikit 1 - On Top of the Rafters": base_location_id + 170,
    "Under the City: Minikit 2 - In Cage Behind Mind Control Door": base_location_id + 171,
    "Under the City: Minikit 3 - In the Glass Room": base_location_id + 172,
    "Under the City: Minikit 4 - On Pipes Above Robin Suit Swapper": base_location_id + 173,
    "Under the City: Minikit 5 - Destroy 5 Markers with Boat Built from Recycler": base_location_id + 174,
    "Under the City: Minikit 6 - Above Ladder Across the Toxic Waste": base_location_id + 175,
    "Under the City: Minikit 7 - Jump From the Toilet": base_location_id + 176,
    "Under the City: Minikit 8 - Above the Scissor Lifter": base_location_id + 177,
    "Under the City: Minikit 9 - Underwater Underneath the Hatch": base_location_id + 178,
    "Under the City: Minikit 10 - On Top of the Pillar by the Generator": base_location_id + 179,

    "Zoo's Company: Minikit 1 - Hit Buoys with Boat Behind Female Locked Room": base_location_id + 180,
    "Zoo's Company: Minikit 2 - In Air on Other Side of Toxic Waste Behind Barred Door": base_location_id + 181,
    "Zoo's Company: Minikit 3 - From the Recycler": base_location_id + 182,
    "Zoo's Company: Minikit 4 - From Destroying Silver Legos Above Recycler": base_location_id + 183,
    "Zoo's Company: Minikit 5 - In the Air After Building Totem": base_location_id + 184,
    "Zoo's Company: Minikit 6 - From Destroying Silver Legos in Lion Enclosure": base_location_id + 185,
    "Zoo's Company: Minikit 7 - In the Elephant Enclosure": base_location_id + 186,
    "Zoo's Company: Minikit 8 - Above Lilypad by the Boat": base_location_id + 187,
    "Zoo's Company: Minikit 9 - On Ledge Behind Waterfall": base_location_id + 188,
    "Zoo's Company: Minikit 10 - Behind Strength Handle by Batman Suit Swapper": base_location_id + 189,

    "Penguin's Lair: Minikit 1 - Under Glass Covered Water": base_location_id + 190,
    "Penguin's Lair: Minikit 2 - In Silver Lego Cage": base_location_id + 191,
    "Penguin's Lair: Minikit 3 - On Roof Above Robin Suit Swapper": base_location_id + 192,
    "Penguin's Lair: Minikit 4 - From Growing 3 Carrots": base_location_id + 193,
    "Penguin's Lair: Minikit 5 - On Icy Ledge": base_location_id + 194,
    "Penguin's Lair: Minikit 6 - On Iceberg in Final Battle Room": base_location_id + 195,
    "Penguin's Lair: Minikit 7 - On South East Ledge in Final Battle Room": base_location_id + 196,
    "Penguin's Lair: Minikit 8 - Behind Silver Lego in Toxic Waste": base_location_id + 197,
    "Penguin's Lair: Minikit 9 - From Destroying the 4 Capacitors with Batarang": base_location_id + 198,
    "Penguin's Lair: Minikit 10 - From Building Heated Objects": base_location_id + 199,

    "Joker's Home Turf: Minikit 1 - Above the Fan Built from Silver Legos": base_location_id + 200,
    "Joker's Home Turf: Minikit 2 - From Cleaning up the Toxic Waste": base_location_id + 201,
    "Joker's Home Turf: Minikit 3 - From Completing the Puzzle Behind the Mind Control Door": base_location_id + 202,
    "Joker's Home Turf: Minikit 4 - Above the Ledge Accessed by Joker's Ladder": base_location_id + 203,
    "Joker's Home Turf: Minikit 5 - Caged in Room Accessed by Controlling Crane": base_location_id + 204,
    "Joker's Home Turf: Minikit 6 - In Toxic Waste Pipe": base_location_id + 205,
    "Joker's Home Turf: Minikit 7 - High Up in Alcove Behind Strength Gate": base_location_id + 206,
    "Joker's Home Turf: Minikit 8 - Crossing the Toxic Waste Water": base_location_id + 207,
    "Joker's Home Turf: Minikit 9 - In Pool of Toxic Waste Drained by Generator": base_location_id + 208,
    "Joker's Home Turf: Minikit 10 - Behind Silver Legos in Mad Hatter Fight": base_location_id + 209,

    "Little Fun at Big Top: Minikit 1 - Across the Tightrope Behind the Pushable Bus": base_location_id + 210,
    "Little Fun at Big Top: Minikit 2 - Carnival Target Game": base_location_id + 211,
    "Little Fun at Big Top: Minikit 3 - Inside Water Filled Pipe Above Carnival Game": base_location_id + 212,
    "Little Fun at Big Top: Minikit 4 - Yellow Duck Carnival Game": base_location_id + 213,
    "Little Fun at Big Top: Minikit 5 - Behind Window Above Gumball Machine": base_location_id + 214,
    "Little Fun at Big Top: Minikit 6 - From Activating Teacup Ride": base_location_id + 215,
    "Little Fun at Big Top: Minikit 7 - On the Spiral Slide": base_location_id + 216,
    "Little Fun at Big Top: Minikit 8 - From Storing the Toy Boats": base_location_id + 217,
    "Little Fun at Big Top: Minikit 9 - Bumper Cars": base_location_id + 218,
    "Little Fun at Big Top: Minikit 10 - Tightrope on the Other Side of the Toxic Waste": base_location_id + 219,

    "Flight of the Bat: Minikit 1 - From Destroying the 6 Missile Launchers": base_location_id + 220,
    "Flight of the Bat: Minikit 2 - Floating by 2 Turrets": base_location_id + 221,
    "Flight of the Bat: Minikit 3 - On the Railway": base_location_id + 222,
    "Flight of the Bat: Minikit 4 - In Silver Lego by Hotel Sign": base_location_id + 223,
    "Flight of the Bat: Minikit 5 - From Destroying the Gray Pipe": base_location_id + 224,
    "Flight of the Bat: Minikit 6 - From Blowing up the Silver Lego Valves": base_location_id + 225,
    "Flight of the Bat: Minikit 7 - From Destroying the 3 Gargoyles": base_location_id + 226,
    "Flight of the Bat: Minikit 8 - From Completing the Barrel Puzzle": base_location_id + 227,
    "Flight of the Bat: Minikit 9 - Platform Near the Helicopter Pad": base_location_id + 228,
    "Flight of the Bat: Minikit 10 - Near the Yellow Barrels on the Rooftop": base_location_id + 229,

    "In the Dark Night: Minikit 1 - From Breaking the Glass Behind the Strength Door": base_location_id + 230,
    "In the Dark Night: Minikit 2 - Back Left Corner of the Rooftop Reached by Grapple": base_location_id + 231,
    "In the Dark Night: Minikit 3 - Destroy Objects to Find 3 Cakes": base_location_id + 232,
    "In the Dark Night: Minikit 4 - In the Fish Tank": base_location_id + 233,
    "In the Dark Night: Minikit 5 - From Flying the Helicopter into 10 Lights": base_location_id + 234,
    "In the Dark Night: Minikit 6 - In the Silver Lego Behind the Garbage Truck": base_location_id + 235,
    "In the Dark Night: Minikit 7 - On the Ledge Next to the Graffiti Wall": base_location_id + 236,
    "In the Dark Night: Minikit 8 - Inside the Silver Lego Manhole Cover": base_location_id + 237,
    "In the Dark Night: Minikit 9 - From Exploding the Generator in the Boss Room": base_location_id + 238,
    "In the Dark Night: Minikit 10 - In Glass Above Joker's Generator": base_location_id + 239,

    "To the Top of the Tower: Minikit 1 - From Destroying 3 Silver Lego Gargoyles": base_location_id + 240,
    "To the Top of the Tower: Minikit 2 - Buttons on the Ledge Above the Flowerbed": base_location_id + 241,
    "To the Top of the Tower: Minikit 3 - Behind the Glass Filled Arch": base_location_id + 242,
    "To the Top of the Tower: Minikit 4 - In the Destroyed Wall by Using the Recycler": base_location_id + 243,
    "To the Top of the Tower: Minikit 5 - Floating on the Right Side of the Cathedral": base_location_id + 244,
    "To the Top of the Tower: Minikit 6 - On Wooden Platform Lowered by Generator": base_location_id + 245,
    "To the Top of the Tower: Minikit 7 - On Ledge Above Magnet Wall": base_location_id + 246,
    "To the Top of the Tower: Minikit 8 - Hidden to the Right of the Lever": base_location_id + 247,
    "To the Top of the Tower: Minikit 9 - Orane Buttons on Left Side of Bell Tower": base_location_id + 248,
    "To the Top of the Tower: Minikit 10 - In the Silver Lego Crate next to Statue Path": base_location_id + 249
}

# hostage_location_table: dict[str, int] = {
    #"You can Bank on Batman: Hostage": base_location_id + 400,
    # "An Icy Reception: Hostage" base_location_id + 401,
    # "A Poisonous Appointment: Hostage", base_location_id + 402,
    # "The Face-Off: Hostage", base_location_id + 403,
    # "There She Goes Again: Hostage", base_location_id + 404,
    # "Under The City: Hostage", base_location_id + 405,
    # "Zoo's Company: Hostage", base_location_id + 406,
    # "Penguin's Lair: Hostage", base_location_id + 407,
    # "Joker's Home Turf: Hostage", base_location_id + 408,
    # "Little Fun at the Big Top: Hostage", base_location_id + 409,
    # "In the Dark Night: Hostage", base_location_id + 410,
    # "To the Top of the Tower: Hostage", base_location_id + 411,
    # "The Riddler Makes a Withdrawal: Hostage", base_location_id + 412,
    # "On the Rocks: Hostage", base_location_id + 413,
    # "Green Fingers: Hostage", base_location_id + 414,
    # "An Enterprising Theft: Hostage", base_location_id + 415,
    # "Breaking Blocks: Hostage", base_location_id + 416,
    # "Rockin' the Docks: Hostage", base_location_id + 417,
    # "Stealing the Show: Hostage", base_location_id + 418,
    # "A Daring Rescue: Hostage", base_location_id + 419,
    # "Arctic World: Hostage", base_location_id + 420,
    # "A Surprise for the Commissioner: Hostage", base_location_id + 421,
    # "The Joker's Masterpiece: Hostage", base_location_id + 422,
    # "The Lure of the Night: Hostage", base_location_id + 423,
    # "Dying of Laughter: Hostage", base_location_id + 424,
# }

location_table = {
    **minikit_location_table,
    # **hostage_location_table
}
