# Region Definitions
# Hub Regions
bc = "Batcave"
aa = "Arkham Asylum"
sh = "Shop"
# Hero Regions
ycbob = "You can Bank on Batman"
air = "An Icy Reception"
tfc = "Two-Face Chase"
apa = "A Poisonous Appointment"
tfo = "The Face-Off"
tsga = "There She Goes Again"
bbb = "Batboat Battle"
utc = "Under the City"
zc = "Zoo's Company"
pl = "Penguin's Lair"
jht = "Joker's Home Turf"
lfabt = "Little Fun at the Big Top"
fotb = "Flight of the Bat"
itdn = "In the Dark Night"
tttot = "To the Top of the Tower"
# Villain Regions
trmaw = "The Riddler Makes a Withdrawal"
otr = "On the Rocks"
gf = "Green Fingers"
aet = "An Enterprising Theft"
bb = "Breaking Blocks"
rtd = "Rockin' the Docks"
sts = "Stealing the Show"
hag = "Harbouring a Grudge"
adr = "A Daring Rescue"
aw = "Arctic World"
asftc = "A Surprise for the Commissioner"
bbpl = "Biplane Blast"
tjm = "The Joker's Masterpiece"
tlotn = "The Lure of the Night"
dol = "Dying of Laughter"
# Freeplay Regions
# Hero Freeplay
ycbobf = "You can Bank on Batman: Freeplay"
airf = "An Icy Reception: Freeplay"
tfcf = "Two-Face Chase: Freeplay"
apaf = "A Poisonous Appointment: Freeplay"
tfof = "The Face-Off: Freeplay"
tsgaf = "There She Goes Again: Freeplay"
bbbf = "Batboat Battle: Freeplay"
utcf = "Under the City: Freeplay"
zcf = "Zoo's Company: Freeplay"
plf = "Penguin's Lair: Freeplay"
jhtf = "Joker's Home Turf: Freeplay"
lfabtf = "Little Fun at the Big Top: Freeplay"
fotbf = "Flight of the Bat: Freeplay"
itdnf = "In the Dark Night: Freeplay"
tttotf = "To the Top of the Tower: Freeplay"
# Villain Freeplay
trmawf = "The Riddler Makes a Withdrawal: Freeplay"
otrf = "On the Rocks: Freeplay"
gff = "Green Fingers: Freeplay"
aetf = "An Enterprising Theft: Freeplay"
bbf = "Breaking Blocks: Freeplay"
rtdf = "Rockin' the Docks: Freeplay"
stsf = "Stealing the Show: Freeplay"
hagf = "Harbouring a Grudge: Freeplay"
adrf = "A Daring Rescue: Freeplay"
awf = "Arctic World: Freeplay"
asftcf = "A Surprise for the Commissioner: Freeplay"
bbplf = "Biplane Blast: Freeplay"
tjmf = "The Joker's Masterpiece: Freeplay"
tlotnf = "The Lure of the Night: Freeplay"
dolf = "Dying of Laughter: Freeplay"
